// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/v1/webapp.proto
// Protobuf Java Version: 4.33.5

package com.common.v1;

/**
 * Protobuf type {@code common.v1.DateFilter}
 */
@com.google.protobuf.Generated
public final class DateFilter extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:common.v1.DateFilter)
    DateFilterOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 5,
      /* suffix= */ "",
      "DateFilter");
  }
  // Use DateFilter.newBuilder() to construct.
  private DateFilter(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private DateFilter() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.common.v1.WebappProto.internal_static_common_v1_DateFilter_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.common.v1.WebappProto.internal_static_common_v1_DateFilter_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.common.v1.DateFilter.class, com.common.v1.DateFilter.Builder.class);
  }

  private int filterCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object filter_;
  public enum FilterCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    RANGE(1),
    EXACT_DATE(2),
    FILTER_NOT_SET(0);
    private final int value;
    private FilterCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FilterCase valueOf(int value) {
      return forNumber(value);
    }

    public static FilterCase forNumber(int value) {
      switch (value) {
        case 1: return RANGE;
        case 2: return EXACT_DATE;
        case 0: return FILTER_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public FilterCase
  getFilterCase() {
    return FilterCase.forNumber(
        filterCase_);
  }

  public static final int RANGE_FIELD_NUMBER = 1;
  /**
   * <code>.common.v1.DateRange range = 1 [json_name = "range"];</code>
   * @return Whether the range field is set.
   */
  @java.lang.Override
  public boolean hasRange() {
    return filterCase_ == 1;
  }
  /**
   * <code>.common.v1.DateRange range = 1 [json_name = "range"];</code>
   * @return The range.
   */
  @java.lang.Override
  public com.common.v1.DateRange getRange() {
    if (filterCase_ == 1) {
       return (com.common.v1.DateRange) filter_;
    }
    return com.common.v1.DateRange.getDefaultInstance();
  }
  /**
   * <code>.common.v1.DateRange range = 1 [json_name = "range"];</code>
   */
  @java.lang.Override
  public com.common.v1.DateRangeOrBuilder getRangeOrBuilder() {
    if (filterCase_ == 1) {
       return (com.common.v1.DateRange) filter_;
    }
    return com.common.v1.DateRange.getDefaultInstance();
  }

  public static final int EXACT_DATE_FIELD_NUMBER = 2;
  /**
   * <code>.google.protobuf.Timestamp exact_date = 2 [json_name = "exactDate"];</code>
   * @return Whether the exactDate field is set.
   */
  @java.lang.Override
  public boolean hasExactDate() {
    return filterCase_ == 2;
  }
  /**
   * <code>.google.protobuf.Timestamp exact_date = 2 [json_name = "exactDate"];</code>
   * @return The exactDate.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getExactDate() {
    if (filterCase_ == 2) {
       return (com.google.protobuf.Timestamp) filter_;
    }
    return com.google.protobuf.Timestamp.getDefaultInstance();
  }
  /**
   * <code>.google.protobuf.Timestamp exact_date = 2 [json_name = "exactDate"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getExactDateOrBuilder() {
    if (filterCase_ == 2) {
       return (com.google.protobuf.Timestamp) filter_;
    }
    return com.google.protobuf.Timestamp.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (filterCase_ == 1) {
      output.writeMessage(1, (com.common.v1.DateRange) filter_);
    }
    if (filterCase_ == 2) {
      output.writeMessage(2, (com.google.protobuf.Timestamp) filter_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (filterCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.common.v1.DateRange) filter_);
    }
    if (filterCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.google.protobuf.Timestamp) filter_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.common.v1.DateFilter)) {
      return super.equals(obj);
    }
    com.common.v1.DateFilter other = (com.common.v1.DateFilter) obj;

    if (!getFilterCase().equals(other.getFilterCase())) return false;
    switch (filterCase_) {
      case 1:
        if (!getRange()
            .equals(other.getRange())) return false;
        break;
      case 2:
        if (!getExactDate()
            .equals(other.getExactDate())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (filterCase_) {
      case 1:
        hash = (37 * hash) + RANGE_FIELD_NUMBER;
        hash = (53 * hash) + getRange().hashCode();
        break;
      case 2:
        hash = (37 * hash) + EXACT_DATE_FIELD_NUMBER;
        hash = (53 * hash) + getExactDate().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.common.v1.DateFilter parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.common.v1.DateFilter parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.common.v1.DateFilter parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.common.v1.DateFilter parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.common.v1.DateFilter parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.common.v1.DateFilter parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.common.v1.DateFilter parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.common.v1.DateFilter parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.common.v1.DateFilter parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.common.v1.DateFilter parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.common.v1.DateFilter parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.common.v1.DateFilter parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.common.v1.DateFilter prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code common.v1.DateFilter}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:common.v1.DateFilter)
      com.common.v1.DateFilterOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.common.v1.WebappProto.internal_static_common_v1_DateFilter_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.common.v1.WebappProto.internal_static_common_v1_DateFilter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.common.v1.DateFilter.class, com.common.v1.DateFilter.Builder.class);
    }

    // Construct using com.common.v1.DateFilter.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (rangeBuilder_ != null) {
        rangeBuilder_.clear();
      }
      if (exactDateBuilder_ != null) {
        exactDateBuilder_.clear();
      }
      filterCase_ = 0;
      filter_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.common.v1.WebappProto.internal_static_common_v1_DateFilter_descriptor;
    }

    @java.lang.Override
    public com.common.v1.DateFilter getDefaultInstanceForType() {
      return com.common.v1.DateFilter.getDefaultInstance();
    }

    @java.lang.Override
    public com.common.v1.DateFilter build() {
      com.common.v1.DateFilter result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.common.v1.DateFilter buildPartial() {
      com.common.v1.DateFilter result = new com.common.v1.DateFilter(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.common.v1.DateFilter result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.common.v1.DateFilter result) {
      result.filterCase_ = filterCase_;
      result.filter_ = this.filter_;
      if (filterCase_ == 1 &&
          rangeBuilder_ != null) {
        result.filter_ = rangeBuilder_.build();
      }
      if (filterCase_ == 2 &&
          exactDateBuilder_ != null) {
        result.filter_ = exactDateBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.common.v1.DateFilter) {
        return mergeFrom((com.common.v1.DateFilter)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.common.v1.DateFilter other) {
      if (other == com.common.v1.DateFilter.getDefaultInstance()) return this;
      switch (other.getFilterCase()) {
        case RANGE: {
          mergeRange(other.getRange());
          break;
        }
        case EXACT_DATE: {
          mergeExactDate(other.getExactDate());
          break;
        }
        case FILTER_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetRangeFieldBuilder().getBuilder(),
                  extensionRegistry);
              filterCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetExactDateFieldBuilder().getBuilder(),
                  extensionRegistry);
              filterCase_ = 2;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int filterCase_ = 0;
    private java.lang.Object filter_;
    public FilterCase
        getFilterCase() {
      return FilterCase.forNumber(
          filterCase_);
    }

    public Builder clearFilter() {
      filterCase_ = 0;
      filter_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilder<
        com.common.v1.DateRange, com.common.v1.DateRange.Builder, com.common.v1.DateRangeOrBuilder> rangeBuilder_;
    /**
     * <code>.common.v1.DateRange range = 1 [json_name = "range"];</code>
     * @return Whether the range field is set.
     */
    @java.lang.Override
    public boolean hasRange() {
      return filterCase_ == 1;
    }
    /**
     * <code>.common.v1.DateRange range = 1 [json_name = "range"];</code>
     * @return The range.
     */
    @java.lang.Override
    public com.common.v1.DateRange getRange() {
      if (rangeBuilder_ == null) {
        if (filterCase_ == 1) {
          return (com.common.v1.DateRange) filter_;
        }
        return com.common.v1.DateRange.getDefaultInstance();
      } else {
        if (filterCase_ == 1) {
          return rangeBuilder_.getMessage();
        }
        return com.common.v1.DateRange.getDefaultInstance();
      }
    }
    /**
     * <code>.common.v1.DateRange range = 1 [json_name = "range"];</code>
     */
    public Builder setRange(com.common.v1.DateRange value) {
      if (rangeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        filter_ = value;
        onChanged();
      } else {
        rangeBuilder_.setMessage(value);
      }
      filterCase_ = 1;
      return this;
    }
    /**
     * <code>.common.v1.DateRange range = 1 [json_name = "range"];</code>
     */
    public Builder setRange(
        com.common.v1.DateRange.Builder builderForValue) {
      if (rangeBuilder_ == null) {
        filter_ = builderForValue.build();
        onChanged();
      } else {
        rangeBuilder_.setMessage(builderForValue.build());
      }
      filterCase_ = 1;
      return this;
    }
    /**
     * <code>.common.v1.DateRange range = 1 [json_name = "range"];</code>
     */
    public Builder mergeRange(com.common.v1.DateRange value) {
      if (rangeBuilder_ == null) {
        if (filterCase_ == 1 &&
            filter_ != com.common.v1.DateRange.getDefaultInstance()) {
          filter_ = com.common.v1.DateRange.newBuilder((com.common.v1.DateRange) filter_)
              .mergeFrom(value).buildPartial();
        } else {
          filter_ = value;
        }
        onChanged();
      } else {
        if (filterCase_ == 1) {
          rangeBuilder_.mergeFrom(value);
        } else {
          rangeBuilder_.setMessage(value);
        }
      }
      filterCase_ = 1;
      return this;
    }
    /**
     * <code>.common.v1.DateRange range = 1 [json_name = "range"];</code>
     */
    public Builder clearRange() {
      if (rangeBuilder_ == null) {
        if (filterCase_ == 1) {
          filterCase_ = 0;
          filter_ = null;
          onChanged();
        }
      } else {
        if (filterCase_ == 1) {
          filterCase_ = 0;
          filter_ = null;
        }
        rangeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.common.v1.DateRange range = 1 [json_name = "range"];</code>
     */
    public com.common.v1.DateRange.Builder getRangeBuilder() {
      return internalGetRangeFieldBuilder().getBuilder();
    }
    /**
     * <code>.common.v1.DateRange range = 1 [json_name = "range"];</code>
     */
    @java.lang.Override
    public com.common.v1.DateRangeOrBuilder getRangeOrBuilder() {
      if ((filterCase_ == 1) && (rangeBuilder_ != null)) {
        return rangeBuilder_.getMessageOrBuilder();
      } else {
        if (filterCase_ == 1) {
          return (com.common.v1.DateRange) filter_;
        }
        return com.common.v1.DateRange.getDefaultInstance();
      }
    }
    /**
     * <code>.common.v1.DateRange range = 1 [json_name = "range"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.common.v1.DateRange, com.common.v1.DateRange.Builder, com.common.v1.DateRangeOrBuilder> 
        internalGetRangeFieldBuilder() {
      if (rangeBuilder_ == null) {
        if (!(filterCase_ == 1)) {
          filter_ = com.common.v1.DateRange.getDefaultInstance();
        }
        rangeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.common.v1.DateRange, com.common.v1.DateRange.Builder, com.common.v1.DateRangeOrBuilder>(
                (com.common.v1.DateRange) filter_,
                getParentForChildren(),
                isClean());
        filter_ = null;
      }
      filterCase_ = 1;
      onChanged();
      return rangeBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> exactDateBuilder_;
    /**
     * <code>.google.protobuf.Timestamp exact_date = 2 [json_name = "exactDate"];</code>
     * @return Whether the exactDate field is set.
     */
    @java.lang.Override
    public boolean hasExactDate() {
      return filterCase_ == 2;
    }
    /**
     * <code>.google.protobuf.Timestamp exact_date = 2 [json_name = "exactDate"];</code>
     * @return The exactDate.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getExactDate() {
      if (exactDateBuilder_ == null) {
        if (filterCase_ == 2) {
          return (com.google.protobuf.Timestamp) filter_;
        }
        return com.google.protobuf.Timestamp.getDefaultInstance();
      } else {
        if (filterCase_ == 2) {
          return exactDateBuilder_.getMessage();
        }
        return com.google.protobuf.Timestamp.getDefaultInstance();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp exact_date = 2 [json_name = "exactDate"];</code>
     */
    public Builder setExactDate(com.google.protobuf.Timestamp value) {
      if (exactDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        filter_ = value;
        onChanged();
      } else {
        exactDateBuilder_.setMessage(value);
      }
      filterCase_ = 2;
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp exact_date = 2 [json_name = "exactDate"];</code>
     */
    public Builder setExactDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (exactDateBuilder_ == null) {
        filter_ = builderForValue.build();
        onChanged();
      } else {
        exactDateBuilder_.setMessage(builderForValue.build());
      }
      filterCase_ = 2;
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp exact_date = 2 [json_name = "exactDate"];</code>
     */
    public Builder mergeExactDate(com.google.protobuf.Timestamp value) {
      if (exactDateBuilder_ == null) {
        if (filterCase_ == 2 &&
            filter_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          filter_ = com.google.protobuf.Timestamp.newBuilder((com.google.protobuf.Timestamp) filter_)
              .mergeFrom(value).buildPartial();
        } else {
          filter_ = value;
        }
        onChanged();
      } else {
        if (filterCase_ == 2) {
          exactDateBuilder_.mergeFrom(value);
        } else {
          exactDateBuilder_.setMessage(value);
        }
      }
      filterCase_ = 2;
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp exact_date = 2 [json_name = "exactDate"];</code>
     */
    public Builder clearExactDate() {
      if (exactDateBuilder_ == null) {
        if (filterCase_ == 2) {
          filterCase_ = 0;
          filter_ = null;
          onChanged();
        }
      } else {
        if (filterCase_ == 2) {
          filterCase_ = 0;
          filter_ = null;
        }
        exactDateBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp exact_date = 2 [json_name = "exactDate"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getExactDateBuilder() {
      return internalGetExactDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp exact_date = 2 [json_name = "exactDate"];</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getExactDateOrBuilder() {
      if ((filterCase_ == 2) && (exactDateBuilder_ != null)) {
        return exactDateBuilder_.getMessageOrBuilder();
      } else {
        if (filterCase_ == 2) {
          return (com.google.protobuf.Timestamp) filter_;
        }
        return com.google.protobuf.Timestamp.getDefaultInstance();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp exact_date = 2 [json_name = "exactDate"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetExactDateFieldBuilder() {
      if (exactDateBuilder_ == null) {
        if (!(filterCase_ == 2)) {
          filter_ = com.google.protobuf.Timestamp.getDefaultInstance();
        }
        exactDateBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                (com.google.protobuf.Timestamp) filter_,
                getParentForChildren(),
                isClean());
        filter_ = null;
      }
      filterCase_ = 2;
      onChanged();
      return exactDateBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:common.v1.DateFilter)
  }

  // @@protoc_insertion_point(class_scope:common.v1.DateFilter)
  private static final com.common.v1.DateFilter DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.common.v1.DateFilter();
  }

  public static com.common.v1.DateFilter getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DateFilter>
      PARSER = new com.google.protobuf.AbstractParser<DateFilter>() {
    @java.lang.Override
    public DateFilter parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DateFilter> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DateFilter> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.common.v1.DateFilter getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

