// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/v1/mfa.proto
// Protobuf Java Version: 4.34.0

package com.common.v1;

/**
 * Protobuf enum {@code common.v1.VerifyErrorType}
 */
@com.google.protobuf.Generated
public enum VerifyErrorType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * OTP verified
   * </pre>
   *
   * <code>VERIFY_ERROR_TYPE_UNSPECIFIED = 0;</code>
   */
  VERIFY_ERROR_TYPE_UNSPECIFIED(0),
  /**
   * <pre>
   * OTP incorrect
   * </pre>
   *
   * <code>VERIFY_ERROR_TYPE_INVALID_OTP = 1;</code>
   */
  VERIFY_ERROR_TYPE_INVALID_OTP(1),
  /**
   * <pre>
   * OTP expired
   * </pre>
   *
   * <code>VERIFY_ERROR_TYPE_EXPIRED = 2;</code>
   */
  VERIFY_ERROR_TYPE_EXPIRED(2),
  /**
   * <pre>
   * Too many failed attempts
   * </pre>
   *
   * <code>VERIFY_ERROR_TYPE_MAX_ATTEMPTS = 3;</code>
   */
  VERIFY_ERROR_TYPE_MAX_ATTEMPTS(3),
  /**
   * <pre>
   * Registration session not found or expired
   * </pre>
   *
   * <code>VERIFY_ERROR_TYPE_INVALID_SESSION = 4;</code>
   */
  VERIFY_ERROR_TYPE_INVALID_SESSION(4),
  /**
   * <pre>
   * No pending verification session exists
   * </pre>
   *
   * <code>VERIFY_ERROR_TYPE_NO_PENDING_VERIFICATION = 5;</code>
   */
  VERIFY_ERROR_TYPE_NO_PENDING_VERIFICATION(5),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "VerifyErrorType");
  }
  /**
   * <pre>
   * OTP verified
   * </pre>
   *
   * <code>VERIFY_ERROR_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int VERIFY_ERROR_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * OTP incorrect
   * </pre>
   *
   * <code>VERIFY_ERROR_TYPE_INVALID_OTP = 1;</code>
   */
  public static final int VERIFY_ERROR_TYPE_INVALID_OTP_VALUE = 1;
  /**
   * <pre>
   * OTP expired
   * </pre>
   *
   * <code>VERIFY_ERROR_TYPE_EXPIRED = 2;</code>
   */
  public static final int VERIFY_ERROR_TYPE_EXPIRED_VALUE = 2;
  /**
   * <pre>
   * Too many failed attempts
   * </pre>
   *
   * <code>VERIFY_ERROR_TYPE_MAX_ATTEMPTS = 3;</code>
   */
  public static final int VERIFY_ERROR_TYPE_MAX_ATTEMPTS_VALUE = 3;
  /**
   * <pre>
   * Registration session not found or expired
   * </pre>
   *
   * <code>VERIFY_ERROR_TYPE_INVALID_SESSION = 4;</code>
   */
  public static final int VERIFY_ERROR_TYPE_INVALID_SESSION_VALUE = 4;
  /**
   * <pre>
   * No pending verification session exists
   * </pre>
   *
   * <code>VERIFY_ERROR_TYPE_NO_PENDING_VERIFICATION = 5;</code>
   */
  public static final int VERIFY_ERROR_TYPE_NO_PENDING_VERIFICATION_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static VerifyErrorType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static VerifyErrorType forNumber(int value) {
    switch (value) {
      case 0: return VERIFY_ERROR_TYPE_UNSPECIFIED;
      case 1: return VERIFY_ERROR_TYPE_INVALID_OTP;
      case 2: return VERIFY_ERROR_TYPE_EXPIRED;
      case 3: return VERIFY_ERROR_TYPE_MAX_ATTEMPTS;
      case 4: return VERIFY_ERROR_TYPE_INVALID_SESSION;
      case 5: return VERIFY_ERROR_TYPE_NO_PENDING_VERIFICATION;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<VerifyErrorType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      VerifyErrorType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<VerifyErrorType>() {
          public VerifyErrorType findValueByNumber(int number) {
            return VerifyErrorType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.common.v1.MfaProto.getDescriptor().getEnumType(2);
  }

  private static final VerifyErrorType[] VALUES = values();

  public static VerifyErrorType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private VerifyErrorType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:common.v1.VerifyErrorType)
}

