// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/payment.proto
// Protobuf Java Version: 4.33.5

package com.api.v1;

/**
 * <pre>
 * # AddChargeResponse
 *
 * This message represents the response after processing an AddChargeRequest.
 * It contains information about the created charge, customer details, and
 * a payment link that can be used to complete the payment if needed.
 * </pre>
 *
 * Protobuf type {@code api.v1.AddChargeResponse}
 */
@com.google.protobuf.Generated
public final class AddChargeResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:api.v1.AddChargeResponse)
    AddChargeResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 5,
      /* suffix= */ "",
      "AddChargeResponse");
  }
  // Use AddChargeResponse.newBuilder() to construct.
  private AddChargeResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AddChargeResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.api.v1.PaymentProto.internal_static_api_v1_AddChargeResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.api.v1.PaymentProto.internal_static_api_v1_AddChargeResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.api.v1.AddChargeResponse.class, com.api.v1.AddChargeResponse.Builder.class);
  }

  private int bitField0_;
  public static final int CHARGE_FIELD_NUMBER = 1;
  private com.api.v1.Charge charge_;
  /**
   * <pre>
   * Charge information for the newly created charge
   * Contains charge ID, status, amount, currency, timestamps, etc.
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>.api.v1.Charge charge = 1 [json_name = "charge", (.buf.validate.field) = { ... }</code>
   * @return Whether the charge field is set.
   */
  @java.lang.Override
  public boolean hasCharge() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Charge information for the newly created charge
   * Contains charge ID, status, amount, currency, timestamps, etc.
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>.api.v1.Charge charge = 1 [json_name = "charge", (.buf.validate.field) = { ... }</code>
   * @return The charge.
   */
  @java.lang.Override
  public com.api.v1.Charge getCharge() {
    return charge_ == null ? com.api.v1.Charge.getDefaultInstance() : charge_;
  }
  /**
   * <pre>
   * Charge information for the newly created charge
   * Contains charge ID, status, amount, currency, timestamps, etc.
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>.api.v1.Charge charge = 1 [json_name = "charge", (.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public com.api.v1.ChargeOrBuilder getChargeOrBuilder() {
    return charge_ == null ? com.api.v1.Charge.getDefaultInstance() : charge_;
  }

  public static final int CUSTOMER_FIELD_NUMBER = 2;
  private com.api.v1.Customer customer_;
  /**
   * <pre>
   * Customer information associated with this charge
   * Contains customer details like name, email, metadata, etc.
   * This is returned for convenience and to confirm the charge association
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>.api.v1.Customer customer = 2 [json_name = "customer", (.buf.validate.field) = { ... }</code>
   * @return Whether the customer field is set.
   */
  @java.lang.Override
  public boolean hasCustomer() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Customer information associated with this charge
   * Contains customer details like name, email, metadata, etc.
   * This is returned for convenience and to confirm the charge association
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>.api.v1.Customer customer = 2 [json_name = "customer", (.buf.validate.field) = { ... }</code>
   * @return The customer.
   */
  @java.lang.Override
  public com.api.v1.Customer getCustomer() {
    return customer_ == null ? com.api.v1.Customer.getDefaultInstance() : customer_;
  }
  /**
   * <pre>
   * Customer information associated with this charge
   * Contains customer details like name, email, metadata, etc.
   * This is returned for convenience and to confirm the charge association
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>.api.v1.Customer customer = 2 [json_name = "customer", (.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public com.api.v1.CustomerOrBuilder getCustomerOrBuilder() {
    return customer_ == null ? com.api.v1.Customer.getDefaultInstance() : customer_;
  }

  public static final int PAYMENT_LINK_FIELD_NUMBER = 3;
  private com.api.v1.PaymentLink paymentLink_;
  /**
   * <pre>
   * Payment link information that can be used to complete the payment
   * For server-initiated charges that require customer action,
   * this link can be presented to the customer to complete the payment flow
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>.api.v1.PaymentLink payment_link = 3 [json_name = "paymentLink", (.buf.validate.field) = { ... }</code>
   * @return Whether the paymentLink field is set.
   */
  @java.lang.Override
  public boolean hasPaymentLink() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * Payment link information that can be used to complete the payment
   * For server-initiated charges that require customer action,
   * this link can be presented to the customer to complete the payment flow
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>.api.v1.PaymentLink payment_link = 3 [json_name = "paymentLink", (.buf.validate.field) = { ... }</code>
   * @return The paymentLink.
   */
  @java.lang.Override
  public com.api.v1.PaymentLink getPaymentLink() {
    return paymentLink_ == null ? com.api.v1.PaymentLink.getDefaultInstance() : paymentLink_;
  }
  /**
   * <pre>
   * Payment link information that can be used to complete the payment
   * For server-initiated charges that require customer action,
   * this link can be presented to the customer to complete the payment flow
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>.api.v1.PaymentLink payment_link = 3 [json_name = "paymentLink", (.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public com.api.v1.PaymentLinkOrBuilder getPaymentLinkOrBuilder() {
    return paymentLink_ == null ? com.api.v1.PaymentLink.getDefaultInstance() : paymentLink_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getCharge());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getCustomer());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getPaymentLink());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCharge());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getCustomer());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getPaymentLink());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.api.v1.AddChargeResponse)) {
      return super.equals(obj);
    }
    com.api.v1.AddChargeResponse other = (com.api.v1.AddChargeResponse) obj;

    if (hasCharge() != other.hasCharge()) return false;
    if (hasCharge()) {
      if (!getCharge()
          .equals(other.getCharge())) return false;
    }
    if (hasCustomer() != other.hasCustomer()) return false;
    if (hasCustomer()) {
      if (!getCustomer()
          .equals(other.getCustomer())) return false;
    }
    if (hasPaymentLink() != other.hasPaymentLink()) return false;
    if (hasPaymentLink()) {
      if (!getPaymentLink()
          .equals(other.getPaymentLink())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCharge()) {
      hash = (37 * hash) + CHARGE_FIELD_NUMBER;
      hash = (53 * hash) + getCharge().hashCode();
    }
    if (hasCustomer()) {
      hash = (37 * hash) + CUSTOMER_FIELD_NUMBER;
      hash = (53 * hash) + getCustomer().hashCode();
    }
    if (hasPaymentLink()) {
      hash = (37 * hash) + PAYMENT_LINK_FIELD_NUMBER;
      hash = (53 * hash) + getPaymentLink().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.api.v1.AddChargeResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.api.v1.AddChargeResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.api.v1.AddChargeResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.api.v1.AddChargeResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.api.v1.AddChargeResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.api.v1.AddChargeResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.api.v1.AddChargeResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.api.v1.AddChargeResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.api.v1.AddChargeResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.api.v1.AddChargeResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.api.v1.AddChargeResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.api.v1.AddChargeResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.api.v1.AddChargeResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * # AddChargeResponse
   *
   * This message represents the response after processing an AddChargeRequest.
   * It contains information about the created charge, customer details, and
   * a payment link that can be used to complete the payment if needed.
   * </pre>
   *
   * Protobuf type {@code api.v1.AddChargeResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.v1.AddChargeResponse)
      com.api.v1.AddChargeResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.api.v1.PaymentProto.internal_static_api_v1_AddChargeResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.api.v1.PaymentProto.internal_static_api_v1_AddChargeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.api.v1.AddChargeResponse.class, com.api.v1.AddChargeResponse.Builder.class);
    }

    // Construct using com.api.v1.AddChargeResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetChargeFieldBuilder();
        internalGetCustomerFieldBuilder();
        internalGetPaymentLinkFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      charge_ = null;
      if (chargeBuilder_ != null) {
        chargeBuilder_.dispose();
        chargeBuilder_ = null;
      }
      customer_ = null;
      if (customerBuilder_ != null) {
        customerBuilder_.dispose();
        customerBuilder_ = null;
      }
      paymentLink_ = null;
      if (paymentLinkBuilder_ != null) {
        paymentLinkBuilder_.dispose();
        paymentLinkBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.api.v1.PaymentProto.internal_static_api_v1_AddChargeResponse_descriptor;
    }

    @java.lang.Override
    public com.api.v1.AddChargeResponse getDefaultInstanceForType() {
      return com.api.v1.AddChargeResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.api.v1.AddChargeResponse build() {
      com.api.v1.AddChargeResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.api.v1.AddChargeResponse buildPartial() {
      com.api.v1.AddChargeResponse result = new com.api.v1.AddChargeResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.api.v1.AddChargeResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.charge_ = chargeBuilder_ == null
            ? charge_
            : chargeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.customer_ = customerBuilder_ == null
            ? customer_
            : customerBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.paymentLink_ = paymentLinkBuilder_ == null
            ? paymentLink_
            : paymentLinkBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.api.v1.AddChargeResponse) {
        return mergeFrom((com.api.v1.AddChargeResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.api.v1.AddChargeResponse other) {
      if (other == com.api.v1.AddChargeResponse.getDefaultInstance()) return this;
      if (other.hasCharge()) {
        mergeCharge(other.getCharge());
      }
      if (other.hasCustomer()) {
        mergeCustomer(other.getCustomer());
      }
      if (other.hasPaymentLink()) {
        mergePaymentLink(other.getPaymentLink());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetChargeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetCustomerFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetPaymentLinkFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.api.v1.Charge charge_;
    private com.google.protobuf.SingleFieldBuilder<
        com.api.v1.Charge, com.api.v1.Charge.Builder, com.api.v1.ChargeOrBuilder> chargeBuilder_;
    /**
     * <pre>
     * Charge information for the newly created charge
     * Contains charge ID, status, amount, currency, timestamps, etc.
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>.api.v1.Charge charge = 1 [json_name = "charge", (.buf.validate.field) = { ... }</code>
     * @return Whether the charge field is set.
     */
    public boolean hasCharge() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Charge information for the newly created charge
     * Contains charge ID, status, amount, currency, timestamps, etc.
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>.api.v1.Charge charge = 1 [json_name = "charge", (.buf.validate.field) = { ... }</code>
     * @return The charge.
     */
    public com.api.v1.Charge getCharge() {
      if (chargeBuilder_ == null) {
        return charge_ == null ? com.api.v1.Charge.getDefaultInstance() : charge_;
      } else {
        return chargeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Charge information for the newly created charge
     * Contains charge ID, status, amount, currency, timestamps, etc.
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>.api.v1.Charge charge = 1 [json_name = "charge", (.buf.validate.field) = { ... }</code>
     */
    public Builder setCharge(com.api.v1.Charge value) {
      if (chargeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        charge_ = value;
      } else {
        chargeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Charge information for the newly created charge
     * Contains charge ID, status, amount, currency, timestamps, etc.
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>.api.v1.Charge charge = 1 [json_name = "charge", (.buf.validate.field) = { ... }</code>
     */
    public Builder setCharge(
        com.api.v1.Charge.Builder builderForValue) {
      if (chargeBuilder_ == null) {
        charge_ = builderForValue.build();
      } else {
        chargeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Charge information for the newly created charge
     * Contains charge ID, status, amount, currency, timestamps, etc.
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>.api.v1.Charge charge = 1 [json_name = "charge", (.buf.validate.field) = { ... }</code>
     */
    public Builder mergeCharge(com.api.v1.Charge value) {
      if (chargeBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          charge_ != null &&
          charge_ != com.api.v1.Charge.getDefaultInstance()) {
          getChargeBuilder().mergeFrom(value);
        } else {
          charge_ = value;
        }
      } else {
        chargeBuilder_.mergeFrom(value);
      }
      if (charge_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Charge information for the newly created charge
     * Contains charge ID, status, amount, currency, timestamps, etc.
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>.api.v1.Charge charge = 1 [json_name = "charge", (.buf.validate.field) = { ... }</code>
     */
    public Builder clearCharge() {
      bitField0_ = (bitField0_ & ~0x00000001);
      charge_ = null;
      if (chargeBuilder_ != null) {
        chargeBuilder_.dispose();
        chargeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Charge information for the newly created charge
     * Contains charge ID, status, amount, currency, timestamps, etc.
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>.api.v1.Charge charge = 1 [json_name = "charge", (.buf.validate.field) = { ... }</code>
     */
    public com.api.v1.Charge.Builder getChargeBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetChargeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Charge information for the newly created charge
     * Contains charge ID, status, amount, currency, timestamps, etc.
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>.api.v1.Charge charge = 1 [json_name = "charge", (.buf.validate.field) = { ... }</code>
     */
    public com.api.v1.ChargeOrBuilder getChargeOrBuilder() {
      if (chargeBuilder_ != null) {
        return chargeBuilder_.getMessageOrBuilder();
      } else {
        return charge_ == null ?
            com.api.v1.Charge.getDefaultInstance() : charge_;
      }
    }
    /**
     * <pre>
     * Charge information for the newly created charge
     * Contains charge ID, status, amount, currency, timestamps, etc.
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>.api.v1.Charge charge = 1 [json_name = "charge", (.buf.validate.field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.api.v1.Charge, com.api.v1.Charge.Builder, com.api.v1.ChargeOrBuilder> 
        internalGetChargeFieldBuilder() {
      if (chargeBuilder_ == null) {
        chargeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.api.v1.Charge, com.api.v1.Charge.Builder, com.api.v1.ChargeOrBuilder>(
                getCharge(),
                getParentForChildren(),
                isClean());
        charge_ = null;
      }
      return chargeBuilder_;
    }

    private com.api.v1.Customer customer_;
    private com.google.protobuf.SingleFieldBuilder<
        com.api.v1.Customer, com.api.v1.Customer.Builder, com.api.v1.CustomerOrBuilder> customerBuilder_;
    /**
     * <pre>
     * Customer information associated with this charge
     * Contains customer details like name, email, metadata, etc.
     * This is returned for convenience and to confirm the charge association
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>.api.v1.Customer customer = 2 [json_name = "customer", (.buf.validate.field) = { ... }</code>
     * @return Whether the customer field is set.
     */
    public boolean hasCustomer() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Customer information associated with this charge
     * Contains customer details like name, email, metadata, etc.
     * This is returned for convenience and to confirm the charge association
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>.api.v1.Customer customer = 2 [json_name = "customer", (.buf.validate.field) = { ... }</code>
     * @return The customer.
     */
    public com.api.v1.Customer getCustomer() {
      if (customerBuilder_ == null) {
        return customer_ == null ? com.api.v1.Customer.getDefaultInstance() : customer_;
      } else {
        return customerBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Customer information associated with this charge
     * Contains customer details like name, email, metadata, etc.
     * This is returned for convenience and to confirm the charge association
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>.api.v1.Customer customer = 2 [json_name = "customer", (.buf.validate.field) = { ... }</code>
     */
    public Builder setCustomer(com.api.v1.Customer value) {
      if (customerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        customer_ = value;
      } else {
        customerBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Customer information associated with this charge
     * Contains customer details like name, email, metadata, etc.
     * This is returned for convenience and to confirm the charge association
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>.api.v1.Customer customer = 2 [json_name = "customer", (.buf.validate.field) = { ... }</code>
     */
    public Builder setCustomer(
        com.api.v1.Customer.Builder builderForValue) {
      if (customerBuilder_ == null) {
        customer_ = builderForValue.build();
      } else {
        customerBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Customer information associated with this charge
     * Contains customer details like name, email, metadata, etc.
     * This is returned for convenience and to confirm the charge association
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>.api.v1.Customer customer = 2 [json_name = "customer", (.buf.validate.field) = { ... }</code>
     */
    public Builder mergeCustomer(com.api.v1.Customer value) {
      if (customerBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          customer_ != null &&
          customer_ != com.api.v1.Customer.getDefaultInstance()) {
          getCustomerBuilder().mergeFrom(value);
        } else {
          customer_ = value;
        }
      } else {
        customerBuilder_.mergeFrom(value);
      }
      if (customer_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Customer information associated with this charge
     * Contains customer details like name, email, metadata, etc.
     * This is returned for convenience and to confirm the charge association
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>.api.v1.Customer customer = 2 [json_name = "customer", (.buf.validate.field) = { ... }</code>
     */
    public Builder clearCustomer() {
      bitField0_ = (bitField0_ & ~0x00000002);
      customer_ = null;
      if (customerBuilder_ != null) {
        customerBuilder_.dispose();
        customerBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Customer information associated with this charge
     * Contains customer details like name, email, metadata, etc.
     * This is returned for convenience and to confirm the charge association
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>.api.v1.Customer customer = 2 [json_name = "customer", (.buf.validate.field) = { ... }</code>
     */
    public com.api.v1.Customer.Builder getCustomerBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetCustomerFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Customer information associated with this charge
     * Contains customer details like name, email, metadata, etc.
     * This is returned for convenience and to confirm the charge association
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>.api.v1.Customer customer = 2 [json_name = "customer", (.buf.validate.field) = { ... }</code>
     */
    public com.api.v1.CustomerOrBuilder getCustomerOrBuilder() {
      if (customerBuilder_ != null) {
        return customerBuilder_.getMessageOrBuilder();
      } else {
        return customer_ == null ?
            com.api.v1.Customer.getDefaultInstance() : customer_;
      }
    }
    /**
     * <pre>
     * Customer information associated with this charge
     * Contains customer details like name, email, metadata, etc.
     * This is returned for convenience and to confirm the charge association
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>.api.v1.Customer customer = 2 [json_name = "customer", (.buf.validate.field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.api.v1.Customer, com.api.v1.Customer.Builder, com.api.v1.CustomerOrBuilder> 
        internalGetCustomerFieldBuilder() {
      if (customerBuilder_ == null) {
        customerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.api.v1.Customer, com.api.v1.Customer.Builder, com.api.v1.CustomerOrBuilder>(
                getCustomer(),
                getParentForChildren(),
                isClean());
        customer_ = null;
      }
      return customerBuilder_;
    }

    private com.api.v1.PaymentLink paymentLink_;
    private com.google.protobuf.SingleFieldBuilder<
        com.api.v1.PaymentLink, com.api.v1.PaymentLink.Builder, com.api.v1.PaymentLinkOrBuilder> paymentLinkBuilder_;
    /**
     * <pre>
     * Payment link information that can be used to complete the payment
     * For server-initiated charges that require customer action,
     * this link can be presented to the customer to complete the payment flow
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>.api.v1.PaymentLink payment_link = 3 [json_name = "paymentLink", (.buf.validate.field) = { ... }</code>
     * @return Whether the paymentLink field is set.
     */
    public boolean hasPaymentLink() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Payment link information that can be used to complete the payment
     * For server-initiated charges that require customer action,
     * this link can be presented to the customer to complete the payment flow
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>.api.v1.PaymentLink payment_link = 3 [json_name = "paymentLink", (.buf.validate.field) = { ... }</code>
     * @return The paymentLink.
     */
    public com.api.v1.PaymentLink getPaymentLink() {
      if (paymentLinkBuilder_ == null) {
        return paymentLink_ == null ? com.api.v1.PaymentLink.getDefaultInstance() : paymentLink_;
      } else {
        return paymentLinkBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Payment link information that can be used to complete the payment
     * For server-initiated charges that require customer action,
     * this link can be presented to the customer to complete the payment flow
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>.api.v1.PaymentLink payment_link = 3 [json_name = "paymentLink", (.buf.validate.field) = { ... }</code>
     */
    public Builder setPaymentLink(com.api.v1.PaymentLink value) {
      if (paymentLinkBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        paymentLink_ = value;
      } else {
        paymentLinkBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Payment link information that can be used to complete the payment
     * For server-initiated charges that require customer action,
     * this link can be presented to the customer to complete the payment flow
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>.api.v1.PaymentLink payment_link = 3 [json_name = "paymentLink", (.buf.validate.field) = { ... }</code>
     */
    public Builder setPaymentLink(
        com.api.v1.PaymentLink.Builder builderForValue) {
      if (paymentLinkBuilder_ == null) {
        paymentLink_ = builderForValue.build();
      } else {
        paymentLinkBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Payment link information that can be used to complete the payment
     * For server-initiated charges that require customer action,
     * this link can be presented to the customer to complete the payment flow
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>.api.v1.PaymentLink payment_link = 3 [json_name = "paymentLink", (.buf.validate.field) = { ... }</code>
     */
    public Builder mergePaymentLink(com.api.v1.PaymentLink value) {
      if (paymentLinkBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          paymentLink_ != null &&
          paymentLink_ != com.api.v1.PaymentLink.getDefaultInstance()) {
          getPaymentLinkBuilder().mergeFrom(value);
        } else {
          paymentLink_ = value;
        }
      } else {
        paymentLinkBuilder_.mergeFrom(value);
      }
      if (paymentLink_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Payment link information that can be used to complete the payment
     * For server-initiated charges that require customer action,
     * this link can be presented to the customer to complete the payment flow
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>.api.v1.PaymentLink payment_link = 3 [json_name = "paymentLink", (.buf.validate.field) = { ... }</code>
     */
    public Builder clearPaymentLink() {
      bitField0_ = (bitField0_ & ~0x00000004);
      paymentLink_ = null;
      if (paymentLinkBuilder_ != null) {
        paymentLinkBuilder_.dispose();
        paymentLinkBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Payment link information that can be used to complete the payment
     * For server-initiated charges that require customer action,
     * this link can be presented to the customer to complete the payment flow
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>.api.v1.PaymentLink payment_link = 3 [json_name = "paymentLink", (.buf.validate.field) = { ... }</code>
     */
    public com.api.v1.PaymentLink.Builder getPaymentLinkBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetPaymentLinkFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Payment link information that can be used to complete the payment
     * For server-initiated charges that require customer action,
     * this link can be presented to the customer to complete the payment flow
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>.api.v1.PaymentLink payment_link = 3 [json_name = "paymentLink", (.buf.validate.field) = { ... }</code>
     */
    public com.api.v1.PaymentLinkOrBuilder getPaymentLinkOrBuilder() {
      if (paymentLinkBuilder_ != null) {
        return paymentLinkBuilder_.getMessageOrBuilder();
      } else {
        return paymentLink_ == null ?
            com.api.v1.PaymentLink.getDefaultInstance() : paymentLink_;
      }
    }
    /**
     * <pre>
     * Payment link information that can be used to complete the payment
     * For server-initiated charges that require customer action,
     * this link can be presented to the customer to complete the payment flow
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>.api.v1.PaymentLink payment_link = 3 [json_name = "paymentLink", (.buf.validate.field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.api.v1.PaymentLink, com.api.v1.PaymentLink.Builder, com.api.v1.PaymentLinkOrBuilder> 
        internalGetPaymentLinkFieldBuilder() {
      if (paymentLinkBuilder_ == null) {
        paymentLinkBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.api.v1.PaymentLink, com.api.v1.PaymentLink.Builder, com.api.v1.PaymentLinkOrBuilder>(
                getPaymentLink(),
                getParentForChildren(),
                isClean());
        paymentLink_ = null;
      }
      return paymentLinkBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:api.v1.AddChargeResponse)
  }

  // @@protoc_insertion_point(class_scope:api.v1.AddChargeResponse)
  private static final com.api.v1.AddChargeResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.api.v1.AddChargeResponse();
  }

  public static com.api.v1.AddChargeResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddChargeResponse>
      PARSER = new com.google.protobuf.AbstractParser<AddChargeResponse>() {
    @java.lang.Override
    public AddChargeResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AddChargeResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AddChargeResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.api.v1.AddChargeResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

