// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/payment.proto
// Protobuf Java Version: 4.34.0

package com.api.v1;

@com.google.protobuf.Generated
public interface AddChargeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.v1.AddChargeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Merchant customer identifier string
   * Must start with "cus-" prefix followed by additional characters
   * This identifier references an existing merchant customer in the system
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>string customer = 1 [json_name = "customer", (.buf.validate.field) = { ... }</code>
   * @return The customer.
   */
  java.lang.String getCustomer();
  /**
   * <pre>
   * Merchant customer identifier string
   * Must start with "cus-" prefix followed by additional characters
   * This identifier references an existing merchant customer in the system
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>string customer = 1 [json_name = "customer", (.buf.validate.field) = { ... }</code>
   * @return The bytes for customer.
   */
  com.google.protobuf.ByteString
      getCustomerBytes();

  /**
   * <pre>
   * The charge details to be processed
   * Contains amount, currency, description, and other charge-specific information
   * Required to process the payment transaction
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>.api.v1.InitialCharge charge = 2 [json_name = "charge", (.buf.validate.field) = { ... }</code>
   * @return Whether the charge field is set.
   */
  boolean hasCharge();
  /**
   * <pre>
   * The charge details to be processed
   * Contains amount, currency, description, and other charge-specific information
   * Required to process the payment transaction
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>.api.v1.InitialCharge charge = 2 [json_name = "charge", (.buf.validate.field) = { ... }</code>
   * @return The charge.
   */
  com.api.v1.InitialCharge getCharge();
  /**
   * <pre>
   * The charge details to be processed
   * Contains amount, currency, description, and other charge-specific information
   * Required to process the payment transaction
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>.api.v1.InitialCharge charge = 2 [json_name = "charge", (.buf.validate.field) = { ... }</code>
   */
  com.api.v1.InitialChargeOrBuilder getChargeOrBuilder();

  /**
   * <pre>
   * Redirect URL to send the customer to after payment processing
   * Redirect URL to send the customer after charge creation
   * This URL is used in the payment flow to redirect the customer
   * after they complete the payment process
   * </pre>
   *
   * <code>optional .api.v1.URL redirect = 10 [json_name = "redirect"];</code>
   * @return Whether the redirect field is set.
   */
  boolean hasRedirect();
  /**
   * <pre>
   * Redirect URL to send the customer to after payment processing
   * Redirect URL to send the customer after charge creation
   * This URL is used in the payment flow to redirect the customer
   * after they complete the payment process
   * </pre>
   *
   * <code>optional .api.v1.URL redirect = 10 [json_name = "redirect"];</code>
   * @return The redirect.
   */
  com.api.v1.URL getRedirect();
  /**
   * <pre>
   * Redirect URL to send the customer to after payment processing
   * Redirect URL to send the customer after charge creation
   * This URL is used in the payment flow to redirect the customer
   * after they complete the payment process
   * </pre>
   *
   * <code>optional .api.v1.URL redirect = 10 [json_name = "redirect"];</code>
   */
  com.api.v1.URLOrBuilder getRedirectOrBuilder();
}
