// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/common.proto
// Protobuf Java Version: 4.33.5

package com.api.v1;

/**
 * <pre>
 * AsyncStatus represents the status of an asynchronous operation.
 * </pre>
 *
 * Protobuf enum {@code api.v1.AsyncStatus}
 */
@com.google.protobuf.Generated
public enum AsyncStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ASYNC_STATUS_UNSPECIFIED = 0;</code>
   */
  ASYNC_STATUS_UNSPECIFIED(0),
  /**
   * <code>ASYNC_STATUS_PENDING = 1;</code>
   */
  ASYNC_STATUS_PENDING(1),
  /**
   * <code>ASYNC_STATUS_RUNNING = 2;</code>
   */
  ASYNC_STATUS_RUNNING(2),
  /**
   * <code>ASYNC_STATUS_SUCCEEDED = 3;</code>
   */
  ASYNC_STATUS_SUCCEEDED(3),
  /**
   * <code>ASYNC_STATUS_FAILED_TO_START = 4;</code>
   */
  ASYNC_STATUS_FAILED_TO_START(4),
  /**
   * <code>ASYNC_STATUS_FAILED = 5;</code>
   */
  ASYNC_STATUS_FAILED(5),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 5,
      /* suffix= */ "",
      "AsyncStatus");
  }
  /**
   * <code>ASYNC_STATUS_UNSPECIFIED = 0;</code>
   */
  public static final int ASYNC_STATUS_UNSPECIFIED_VALUE = 0;
  /**
   * <code>ASYNC_STATUS_PENDING = 1;</code>
   */
  public static final int ASYNC_STATUS_PENDING_VALUE = 1;
  /**
   * <code>ASYNC_STATUS_RUNNING = 2;</code>
   */
  public static final int ASYNC_STATUS_RUNNING_VALUE = 2;
  /**
   * <code>ASYNC_STATUS_SUCCEEDED = 3;</code>
   */
  public static final int ASYNC_STATUS_SUCCEEDED_VALUE = 3;
  /**
   * <code>ASYNC_STATUS_FAILED_TO_START = 4;</code>
   */
  public static final int ASYNC_STATUS_FAILED_TO_START_VALUE = 4;
  /**
   * <code>ASYNC_STATUS_FAILED = 5;</code>
   */
  public static final int ASYNC_STATUS_FAILED_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static AsyncStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static AsyncStatus forNumber(int value) {
    switch (value) {
      case 0: return ASYNC_STATUS_UNSPECIFIED;
      case 1: return ASYNC_STATUS_PENDING;
      case 2: return ASYNC_STATUS_RUNNING;
      case 3: return ASYNC_STATUS_SUCCEEDED;
      case 4: return ASYNC_STATUS_FAILED_TO_START;
      case 5: return ASYNC_STATUS_FAILED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AsyncStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AsyncStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AsyncStatus>() {
          public AsyncStatus findValueByNumber(int number) {
            return AsyncStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.api.v1.CommonProto.getDescriptor().getEnumTypes().get(4);
  }

  private static final AsyncStatus[] VALUES = values();

  public static AsyncStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private AsyncStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:api.v1.AsyncStatus)
}

