// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/payment.proto
// Protobuf Java Version: 4.34.1

package com.api.v1;

@com.google.protobuf.Generated
public interface ChargeErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.v1.ChargeError)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Jamm defined error code (e.g. "ERROR_TYPE_PAYMENT_CHARGE_OVER_LIMIT").
   * </pre>
   *
   * <code>string code = 1 [json_name = "code", (.buf.validate.field) = { ... }</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <pre>
   * Jamm defined error code (e.g. "ERROR_TYPE_PAYMENT_CHARGE_OVER_LIMIT").
   * </pre>
   *
   * <code>string code = 1 [json_name = "code", (.buf.validate.field) = { ... }</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <pre>
   * Human readable error message.
   * </pre>
   *
   * <code>string message = 2 [json_name = "message", (.buf.validate.field) = { ... }</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Human readable error message.
   * </pre>
   *
   * <code>string message = 2 [json_name = "message", (.buf.validate.field) = { ... }</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
