// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/merchant_webhooks.proto
// Protobuf Java Version: 4.33.5

package com.api.v1;

@com.google.protobuf.Generated
public interface ChargeMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.v1.ChargeMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string customer = 2 [json_name = "customer", (.buf.validate.field) = { ... }</code>
   * @return The customer.
   */
  java.lang.String getCustomer();
  /**
   * <code>string customer = 2 [json_name = "customer", (.buf.validate.field) = { ... }</code>
   * @return The bytes for customer.
   */
  com.google.protobuf.ByteString
      getCustomerBytes();

  /**
   * <code>.api.v1.ChargeMessage.Status status = 3 [json_name = "status", (.buf.validate.field) = { ... }</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.api.v1.ChargeMessage.Status status = 3 [json_name = "status", (.buf.validate.field) = { ... }</code>
   * @return The status.
   */
  com.api.v1.ChargeMessage.Status getStatus();

  /**
   * <code>string description = 4 [json_name = "description", (.buf.validate.field) = { ... }</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 4 [json_name = "description", (.buf.validate.field) = { ... }</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string merchant_name = 5 [json_name = "merchantName", (.buf.validate.field) = { ... }</code>
   * @return The merchantName.
   */
  java.lang.String getMerchantName();
  /**
   * <code>string merchant_name = 5 [json_name = "merchantName", (.buf.validate.field) = { ... }</code>
   * @return The bytes for merchantName.
   */
  com.google.protobuf.ByteString
      getMerchantNameBytes();

  /**
   * <code>int32 initial_amount = 6 [json_name = "initialAmount", (.buf.validate.field) = { ... }</code>
   * @return The initialAmount.
   */
  int getInitialAmount();

  /**
   * <code>int32 discount = 7 [json_name = "discount", (.buf.validate.field) = { ... }</code>
   * @return The discount.
   */
  int getDiscount();

  /**
   * <code>int32 final_amount = 8 [json_name = "finalAmount", (.buf.validate.field) = { ... }</code>
   * @return The finalAmount.
   */
  int getFinalAmount();

  /**
   * <code>optional int32 amount_refunded = 9 [json_name = "amountRefunded"];</code>
   * @return Whether the amountRefunded field is set.
   */
  boolean hasAmountRefunded();
  /**
   * <code>optional int32 amount_refunded = 9 [json_name = "amountRefunded"];</code>
   * @return The amountRefunded.
   */
  int getAmountRefunded();

  /**
   * <code>string currency = 10 [json_name = "currency", (.buf.validate.field) = { ... }</code>
   * @return The currency.
   */
  java.lang.String getCurrency();
  /**
   * <code>string currency = 10 [json_name = "currency", (.buf.validate.field) = { ... }</code>
   * @return The bytes for currency.
   */
  com.google.protobuf.ByteString
      getCurrencyBytes();

  /**
   * <code>optional string processed_at = 11 [json_name = "processedAt"];</code>
   * @return Whether the processedAt field is set.
   */
  boolean hasProcessedAt();
  /**
   * <code>optional string processed_at = 11 [json_name = "processedAt"];</code>
   * @return The processedAt.
   */
  java.lang.String getProcessedAt();
  /**
   * <code>optional string processed_at = 11 [json_name = "processedAt"];</code>
   * @return The bytes for processedAt.
   */
  com.google.protobuf.ByteString
      getProcessedAtBytes();

  /**
   * <code>string created_at = 13 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
   * @return The createdAt.
   */
  java.lang.String getCreatedAt();
  /**
   * <code>string created_at = 13 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
   * @return The bytes for createdAt.
   */
  com.google.protobuf.ByteString
      getCreatedAtBytes();

  /**
   * <code>string updated_at = 14 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
   * @return The updatedAt.
   */
  java.lang.String getUpdatedAt();
  /**
   * <code>string updated_at = 14 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
   * @return The bytes for updatedAt.
   */
  com.google.protobuf.ByteString
      getUpdatedAtBytes();

  /**
   * <code>optional .api.v1.Error error = 20 [json_name = "error"];</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>optional .api.v1.Error error = 20 [json_name = "error"];</code>
   * @return The error.
   */
  com.api.v1.Error getError();
  /**
   * <code>optional .api.v1.Error error = 20 [json_name = "error"];</code>
   */
  com.api.v1.ErrorOrBuilder getErrorOrBuilder();
}
