// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/common.proto
// Protobuf Java Version: 4.34.1

package com.api.v1;

@com.google.protobuf.Generated
public final class CommonProto extends com.google.protobuf.GeneratedFile {
  private CommonProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "CommonProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_Buyer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_Buyer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_Buyer_MetadataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_Buyer_MetadataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_MerchantCustomer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_MerchantCustomer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_Customer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_Customer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_Status_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_Status_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_BankInformation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_BankInformation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_Merchant_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_Merchant_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_Contract_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_Contract_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_Pagination_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_Pagination_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_Bank_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_Bank_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_BankQuota_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_BankQuota_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_BankScheduledMaintenancePeriod_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_BankScheduledMaintenancePeriod_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_BankBranch_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_BankBranch_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_BankAssets_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_BankAssets_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023api/v1/common.proto\022\006api.v1\032\037google/pr" +
      "otobuf/timestamp.proto\"\367\004\n\005Buyer\022\026\n\005emai" +
      "l\030\001 \001(\tB\000R\005email\022\033\n\tforce_kyc\030\002 \001(\010R\010for" +
      "ceKyc\022\033\n\005phone\030\003 \001(\tB\000H\000R\005phone\210\001\001\022\031\n\004na" +
      "me\030\004 \001(\tB\000H\001R\004name\210\001\001\0223\n\022katakana_last_n" +
      "ame\030\013 \001(\tB\000H\002R\020katakanaLastName\210\001\001\0225\n\023ka" +
      "takana_first_name\030\014 \001(\tB\000H\003R\021katakanaFir" +
      "stName\210\001\001\022\037\n\007address\030\r \001(\tB\000H\004R\007address\210" +
      "\001\001\022$\n\nbirth_date\030\024 \001(\tB\000H\005R\tbirthDate\210\001\001" +
      "\022\035\n\006gender\030\025 \001(\tB\000H\006R\006gender\210\001\001\022@\n\nexpir" +
      "es_at\030\026 \001(\0132\032.google.protobuf.TimestampB" +
      "\000H\007R\texpiresAt\210\001\001\0229\n\010metadata\030\036 \003(\0132\033.ap" +
      "i.v1.Buyer.MetadataEntryB\000R\010metadata\032;\n\r" +
      "MetadataEntry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005value" +
      "\030\002 \001(\tR\005value:\0028\001B\010\n\006_phoneB\007\n\005_nameB\025\n\023" +
      "_katakana_last_nameB\026\n\024_katakana_first_n" +
      "ameB\n\n\010_addressB\r\n\013_birth_dateB\t\n\007_gende" +
      "rB\r\n\013_expires_at\"r\n\020MerchantCustomer\022.\n\010" +
      "customer\030\001 \001(\0132\020.api.v1.CustomerB\000R\010cust" +
      "omer\022.\n\010merchant\030\002 \001(\0132\020.api.v1.Merchant" +
      "B\000R\010merchant\"\345\002\n\010Customer\022\020\n\002id\030\001 \001(\tB\000R" +
      "\002id\022\026\n\005email\030\002 \001(\tB\000R\005email\022)\n\020link_init" +
      "ialized\030\003 \001(\010R\017linkInitialized\022\034\n\tactiva" +
      "ted\030\004 \001(\010R\tactivated\022(\n\006status\030\005 \001(\0132\016.a" +
      "pi.v1.StatusB\000R\006status\022B\n\020bank_informati" +
      "on\030\006 \001(\0132\027.api.v1.BankInformationR\017bankI" +
      "nformation\022;\n\ncreated_at\030\n \001(\0132\032.google." +
      "protobuf.TimestampB\000R\tcreatedAt\022;\n\nupdat" +
      "ed_at\030\013 \001(\0132\032.google.protobuf.TimestampB" +
      "\000R\tupdatedAt\"o\n\006Status\022>\n\007payment\030\001 \001(\0162" +
      "\".api.v1.PaymentAuthorizationStatusB\000R\007p" +
      "ayment\022%\n\003kyc\030\002 \001(\0162\021.api.v1.KycStatusB\000" +
      "R\003kyc\"\266\001\n\017BankInformation\022\'\n\016account_num" +
      "ber\030\001 \001(\tB\000R\raccountNumber\022\035\n\tbank_name\030" +
      "\002 \001(\tB\000R\010bankName\022!\n\013branch_name\030\003 \001(\tB\000" +
      "R\nbranchName\0228\n\014deposit_type\030\004 \001(\0162\023.api" +
      ".v1.DepositTypeB\000R\013depositType\"2\n\010Mercha" +
      "nt\022\020\n\002id\030\001 \001(\tB\000R\002id\022\024\n\004name\030\002 \001(\tB\000R\004na" +
      "me\"\310\001\n\010Contract\022\020\n\002id\030\001 \001(\tB\000R\002id\0220\n\006sta" +
      "tus\030\002 \001(\0162\026.api.v1.ContractStatusB\000R\006sta" +
      "tus\022;\n\ncreated_at\030\024 \001(\0132\032.google.protobu" +
      "f.TimestampB\000R\tcreatedAt\022;\n\nupdated_at\030\025" +
      " \001(\0132\032.google.protobuf.TimestampB\000R\tupda" +
      "tedAt\"J\n\nPagination\022\035\n\tpage_size\030\001 \001(\005B\000" +
      "R\010pageSize\022\035\n\npage_token\030\002 \001(\tR\tpageToke" +
      "n\"\236\006\n\004Bank\022\024\n\004code\030\001 \001(\tB\000R\004code\022\024\n\004name" +
      "\030\002 \001(\tB\000R\004name\022%\n\rname_katakana\030\003 \001(\tB\000R" +
      "\014nameKatakana\022%\n\rname_hiragana\030\004 \001(\tB\000R\014" +
      "nameHiragana\022%\n\rname_alphabet\030\005 \001(\tB\000R\014n" +
      "ameAlphabet\022,\n\006assets\030\013 \001(\0132\022.api.v1.Ban" +
      "kAssetsB\000R\006assets\022)\n\005quota\030\024 \001(\0132\021.api.v" +
      "1.BankQuotaB\000R\005quota\022%\n\ropening_hours\030\036 " +
      "\001(\tB\000R\014openingHours\022l\n\036bankpay_scheduled" +
      "_maintenances\030( \003(\0132&.api.v1.BankSchedul" +
      "edMaintenancePeriodR\034bankpayScheduledMai" +
      "ntenances\022f\n\033bank_scheduled_maintenances" +
      "\030) \003(\0132&.api.v1.BankScheduledMaintenance" +
      "PeriodR\031bankScheduledMaintenances\022v\n#reg" +
      "istration_scheduled_maintenances\030* \003(\0132&" +
      ".api.v1.BankScheduledMaintenancePeriodR!" +
      "registrationScheduledMaintenances\022+\n\021ban" +
      "kpay_available\0302 \001(\010R\020bankpayAvailable\022%" +
      "\n\016bank_available\0303 \001(\010R\rbankAvailable\0225\n" +
      "\026registration_available\0304 \001(\010R\025registrat" +
      "ionAvailable\022\034\n\toperating\030c \001(\010R\toperati" +
      "ng\"\223\006\n\tBankQuota\022Z\n*offline_purchase_lim" +
      "it_per_charge_with_kyc\030\001 \001(\005B\000R$offlineP" +
      "urchaseLimitPerChargeWithKyc\022`\n-offline_" +
      "purchase_limit_per_charge_without_kyc\030\002 " +
      "\001(\005B\000R\'offlinePurchaseLimitPerChargeWith" +
      "outKyc\022T\n\'offline_purchase_limit_per_day" +
      "_with_kyc\030\n \001(\005B\000R!offlinePurchaseLimitP" +
      "erDayWithKyc\022Z\n*offline_purchase_limit_p" +
      "er_day_without_kyc\030\013 \001(\005B\000R$offlinePurch" +
      "aseLimitPerDayWithoutKyc\022d\n/subscription" +
      "_purchase_limit_per_charge_with_kyc\030\024 \001(" +
      "\005B\000R)subscriptionPurchaseLimitPerChargeW" +
      "ithKyc\022j\n2subscription_purchase_limit_pe" +
      "r_charge_without_kyc\030\025 \001(\005B\000R,subscripti" +
      "onPurchaseLimitPerChargeWithoutKyc\022^\n,su" +
      "bscription_purchase_limit_per_day_with_k" +
      "yc\030\036 \001(\005B\000R&subscriptionPurchaseLimitPer" +
      "DayWithKyc\022d\n/subscription_purchase_limi" +
      "t_per_day_without_kyc\030\037 \001(\005B\000R)subscript" +
      "ionPurchaseLimitPerDayWithoutKyc\"\307\001\n\036Ban" +
      "kScheduledMaintenancePeriod\022\035\n\tbank_code" +
      "\030\001 \001(\tB\000R\010bankCode\022\"\n\014start_at_jst\030\002 \001(\t" +
      "B\000R\nstartAtJst\022\036\n\nend_at_jst\030\003 \001(\tB\000R\010en" +
      "dAtJst\022\"\n\014start_at_utc\030\004 \001(\tB\000R\nstartAtU" +
      "tc\022\036\n\nend_at_utc\030\005 \001(\tB\000R\010endAtUtc\"\325\001\n\nB" +
      "ankBranch\022\035\n\tbank_code\030\001 \001(\tB\000R\010bankCode" +
      "\022!\n\013branch_code\030\002 \001(\tB\000R\nbranchCode\022\024\n\004n" +
      "ame\030\003 \001(\tB\000R\004name\022#\n\rname_katakana\030\004 \001(\t" +
      "R\014nameKatakana\022%\n\rname_hiragana\030\005 \001(\tB\000R" +
      "\014nameHiragana\022#\n\rname_alphabet\030\006 \001(\tR\014na" +
      "meAlphabet\"\230\001\n\nBankAssets\022\035\n\tbank_code\030\001" +
      " \001(\tB\000R\010bankCode\022$\n\016logo_url_large\030\002 \001(\t" +
      "R\014logoUrlLarge\022&\n\017logo_url_medium\030\003 \001(\tR" +
      "\rlogoUrlMedium\022\035\n\tterms_url\030\n \001(\tB\000R\010ter" +
      "msUrl*`\n\013DepositType\022\034\n\030DEPOSIT_TYPE_UNS" +
      "PECIFIED\020\000\022\030\n\024DEPOSIT_TYPE_SAVINGS\020\001\022\031\n\025" +
      "DEPOSIT_TYPE_CHECKING\020\002*\250\001\n\032PaymentAutho" +
      "rizationStatus\022,\n(PAYMENT_AUTHORIZATION_" +
      "STATUS_UNSPECIFIED\020\000\022+\n\'PAYMENT_AUTHORIZ" +
      "ATION_STATUS_AUTHORIZED\020\001\022/\n+PAYMENT_AUT" +
      "HORIZATION_STATUS_NOT_AUTHORIZED\020\002*\217\001\n\tK" +
      "ycStatus\022\032\n\026KYC_STATUS_UNSPECIFIED\020\000\022\027\n\023" +
      "KYC_STATUS_APPROVED\020\001\022\034\n\030KYC_STATUS_NOT_" +
      "SUBMITTED\020\002\022\030\n\024KYC_STATUS_IN_REVIEW\020\003\022\025\n" +
      "\021KYC_STATUS_DENIED\020\004*\256\002\n\016ContractStatus\022" +
      "\037\n\033CONTRACT_STATUS_UNSPECIFIED\020\000\022\033\n\027CONT" +
      "RACT_STATUS_INITIAL\020\001\022\034\n\030CONTRACT_STATUS" +
      "_APPROVED\020\002\022\035\n\031CONTRACT_STATUS_ACTIVATED" +
      "\020\003\022 \n\034CONTRACT_STATUS_WAITING_EKYC\020\004\022\033\n\027" +
      "CONTRACT_STATUS_EXPIRED\020\005\022\037\n\033CONTRACT_ST" +
      "ATUS_DEACTIVATED\020\006\022\035\n\031CONTRACT_STATUS_CA" +
      "NCELLED\020\007\022\"\n\036CONTRACT_STATUS_PENDING_CHA" +
      "RGE\020\010*\266\001\n\013AsyncStatus\022\034\n\030ASYNC_STATUS_UN" +
      "SPECIFIED\020\000\022\030\n\024ASYNC_STATUS_PENDING\020\001\022\030\n" +
      "\024ASYNC_STATUS_RUNNING\020\002\022\032\n\026ASYNC_STATUS_" +
      "SUCCEEDED\020\003\022 \n\034ASYNC_STATUS_FAILED_TO_ST" +
      "ART\020\004\022\027\n\023ASYNC_STATUS_FAILED\020\005*\363\001\n\014Charg" +
      "eStatus\022\035\n\031CHARGE_STATUS_UNSPECIFIED\020\000\022\031" +
      "\n\025CHARGE_STATUS_SUCCESS\020\001\022\031\n\025CHARGE_STAT" +
      "US_FAILURE\020\002\022\036\n\032CHARGE_STATUS_WAITING_EK" +
      "YC\020\003\022\032\n\026CHARGE_STATUS_BLOCKING\020\004\022\033\n\027CHAR" +
      "GE_STATUS_CANCELLED\020\005\022\032\n\026CHARGE_STATUS_R" +
      "EFUNDED\020\006\022\031\n\025CHARGE_STATUS_PENDING\020\007Bo\n\n" +
      "com.api.v1B\013CommonProtoP\001Z\033api/proto/gen" +
      "/api/v1;api_v1\242\002\003AXX\252\002\006Api.V1\312\002\006Api\\V1\342\002" +
      "\022Api\\V1\\GPBMetadata\352\002\007Api::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_api_v1_Buyer_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_api_v1_Buyer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_Buyer_descriptor,
        new java.lang.String[] { "Email", "ForceKyc", "Phone", "Name", "KatakanaLastName", "KatakanaFirstName", "Address", "BirthDate", "Gender", "ExpiresAt", "Metadata", });
    internal_static_api_v1_Buyer_MetadataEntry_descriptor =
      internal_static_api_v1_Buyer_descriptor.getNestedType(0);
    internal_static_api_v1_Buyer_MetadataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_Buyer_MetadataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_api_v1_MerchantCustomer_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_api_v1_MerchantCustomer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_MerchantCustomer_descriptor,
        new java.lang.String[] { "Customer", "Merchant", });
    internal_static_api_v1_Customer_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_api_v1_Customer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_Customer_descriptor,
        new java.lang.String[] { "Id", "Email", "LinkInitialized", "Activated", "Status", "BankInformation", "CreatedAt", "UpdatedAt", });
    internal_static_api_v1_Status_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_api_v1_Status_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_Status_descriptor,
        new java.lang.String[] { "Payment", "Kyc", });
    internal_static_api_v1_BankInformation_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_api_v1_BankInformation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_BankInformation_descriptor,
        new java.lang.String[] { "AccountNumber", "BankName", "BranchName", "DepositType", });
    internal_static_api_v1_Merchant_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_api_v1_Merchant_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_Merchant_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_api_v1_Contract_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_api_v1_Contract_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_Contract_descriptor,
        new java.lang.String[] { "Id", "Status", "CreatedAt", "UpdatedAt", });
    internal_static_api_v1_Pagination_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_api_v1_Pagination_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_Pagination_descriptor,
        new java.lang.String[] { "PageSize", "PageToken", });
    internal_static_api_v1_Bank_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_api_v1_Bank_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_Bank_descriptor,
        new java.lang.String[] { "Code", "Name", "NameKatakana", "NameHiragana", "NameAlphabet", "Assets", "Quota", "OpeningHours", "BankpayScheduledMaintenances", "BankScheduledMaintenances", "RegistrationScheduledMaintenances", "BankpayAvailable", "BankAvailable", "RegistrationAvailable", "Operating", });
    internal_static_api_v1_BankQuota_descriptor =
      getDescriptor().getMessageType(9);
    internal_static_api_v1_BankQuota_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_BankQuota_descriptor,
        new java.lang.String[] { "OfflinePurchaseLimitPerChargeWithKyc", "OfflinePurchaseLimitPerChargeWithoutKyc", "OfflinePurchaseLimitPerDayWithKyc", "OfflinePurchaseLimitPerDayWithoutKyc", "SubscriptionPurchaseLimitPerChargeWithKyc", "SubscriptionPurchaseLimitPerChargeWithoutKyc", "SubscriptionPurchaseLimitPerDayWithKyc", "SubscriptionPurchaseLimitPerDayWithoutKyc", });
    internal_static_api_v1_BankScheduledMaintenancePeriod_descriptor =
      getDescriptor().getMessageType(10);
    internal_static_api_v1_BankScheduledMaintenancePeriod_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_BankScheduledMaintenancePeriod_descriptor,
        new java.lang.String[] { "BankCode", "StartAtJst", "EndAtJst", "StartAtUtc", "EndAtUtc", });
    internal_static_api_v1_BankBranch_descriptor =
      getDescriptor().getMessageType(11);
    internal_static_api_v1_BankBranch_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_BankBranch_descriptor,
        new java.lang.String[] { "BankCode", "BranchCode", "Name", "NameKatakana", "NameHiragana", "NameAlphabet", });
    internal_static_api_v1_BankAssets_descriptor =
      getDescriptor().getMessageType(12);
    internal_static_api_v1_BankAssets_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_BankAssets_descriptor,
        new java.lang.String[] { "BankCode", "LogoUrlLarge", "LogoUrlMedium", "TermsUrl", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
