// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/common.proto
// Protobuf Java Version: 4.33.5

package com.api.v1;

/**
 * <pre>
 * Contract represents a payment agreement between the Jamm customer and the merchant.
 * Merchant must use the contract ID to further make a charge, therefore please persist
 * this ID into your database.
 *
 * 契約はJammの顧客とショップの間の支払い契約を表します。
 * ショップは契約IDを使用して決済を行う必要がありますので、このIDはデータベースに保存してください。
 * </pre>
 *
 * Protobuf type {@code api.v1.Contract}
 */
@com.google.protobuf.Generated
public final class Contract extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:api.v1.Contract)
    ContractOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 5,
      /* suffix= */ "",
      "Contract");
  }
  // Use Contract.newBuilder() to construct.
  private Contract(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Contract() {
    id_ = "";
    status_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.api.v1.CommonProto.internal_static_api_v1_Contract_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.api.v1.CommonProto.internal_static_api_v1_Contract_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.api.v1.Contract.class, com.api.v1.Contract.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <pre>
   * Contract ID (e.g. con-1234567890)
   *
   * 契約ID (例: con-1234567890)
   *
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Contract ID (e.g. con-1234567890)
   *
   * 契約ID (例: con-1234567890)
   *
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  private int status_ = 0;
  /**
   * <pre>
   * Status of the contract.
   * </pre>
   *
   * <code>.api.v1.ContractStatus status = 2 [json_name = "status", (.buf.validate.field) = { ... }</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <pre>
   * Status of the contract.
   * </pre>
   *
   * <code>.api.v1.ContractStatus status = 2 [json_name = "status", (.buf.validate.field) = { ... }</code>
   * @return The status.
   */
  @java.lang.Override public com.api.v1.ContractStatus getStatus() {
    com.api.v1.ContractStatus result = com.api.v1.ContractStatus.forNumber(status_);
    return result == null ? com.api.v1.ContractStatus.UNRECOGNIZED : result;
  }

  public static final int CREATED_AT_FIELD_NUMBER = 20;
  private com.google.protobuf.Timestamp createdAt_;
  /**
   * <pre>
   * Created date of the contract.
   *
   * 契約の作成日時。
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 20 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
   * @return Whether the createdAt field is set.
   */
  @java.lang.Override
  public boolean hasCreatedAt() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Created date of the contract.
   *
   * 契約の作成日時。
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 20 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
   * @return The createdAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreatedAt() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }
  /**
   * <pre>
   * Created date of the contract.
   *
   * 契約の作成日時。
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 20 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }

  public static final int UPDATED_AT_FIELD_NUMBER = 21;
  private com.google.protobuf.Timestamp updatedAt_;
  /**
   * <pre>
   * Updated date of the contract.
   *
   * 契約の更新日時。
   * </pre>
   *
   * <code>.google.protobuf.Timestamp updated_at = 21 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
   * @return Whether the updatedAt field is set.
   */
  @java.lang.Override
  public boolean hasUpdatedAt() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Updated date of the contract.
   *
   * 契約の更新日時。
   * </pre>
   *
   * <code>.google.protobuf.Timestamp updated_at = 21 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
   * @return The updatedAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getUpdatedAt() {
    return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
  }
  /**
   * <pre>
   * Updated date of the contract.
   *
   * 契約の更新日時。
   * </pre>
   *
   * <code>.google.protobuf.Timestamp updated_at = 21 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
    return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
    }
    if (status_ != com.api.v1.ContractStatus.CONTRACT_STATUS_UNSPECIFIED.getNumber()) {
      output.writeEnum(2, status_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(20, getCreatedAt());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(21, getUpdatedAt());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
    }
    if (status_ != com.api.v1.ContractStatus.CONTRACT_STATUS_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, status_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(20, getCreatedAt());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(21, getUpdatedAt());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.api.v1.Contract)) {
      return super.equals(obj);
    }
    com.api.v1.Contract other = (com.api.v1.Contract) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (status_ != other.status_) return false;
    if (hasCreatedAt() != other.hasCreatedAt()) return false;
    if (hasCreatedAt()) {
      if (!getCreatedAt()
          .equals(other.getCreatedAt())) return false;
    }
    if (hasUpdatedAt() != other.hasUpdatedAt()) return false;
    if (hasUpdatedAt()) {
      if (!getUpdatedAt()
          .equals(other.getUpdatedAt())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    if (hasCreatedAt()) {
      hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getCreatedAt().hashCode();
    }
    if (hasUpdatedAt()) {
      hash = (37 * hash) + UPDATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getUpdatedAt().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.api.v1.Contract parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.api.v1.Contract parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.api.v1.Contract parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.api.v1.Contract parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.api.v1.Contract parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.api.v1.Contract parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.api.v1.Contract parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.api.v1.Contract parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.api.v1.Contract parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.api.v1.Contract parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.api.v1.Contract parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.api.v1.Contract parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.api.v1.Contract prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Contract represents a payment agreement between the Jamm customer and the merchant.
   * Merchant must use the contract ID to further make a charge, therefore please persist
   * this ID into your database.
   *
   * 契約はJammの顧客とショップの間の支払い契約を表します。
   * ショップは契約IDを使用して決済を行う必要がありますので、このIDはデータベースに保存してください。
   * </pre>
   *
   * Protobuf type {@code api.v1.Contract}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.v1.Contract)
      com.api.v1.ContractOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.api.v1.CommonProto.internal_static_api_v1_Contract_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.api.v1.CommonProto.internal_static_api_v1_Contract_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.api.v1.Contract.class, com.api.v1.Contract.Builder.class);
    }

    // Construct using com.api.v1.Contract.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetCreatedAtFieldBuilder();
        internalGetUpdatedAtFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      status_ = 0;
      createdAt_ = null;
      if (createdAtBuilder_ != null) {
        createdAtBuilder_.dispose();
        createdAtBuilder_ = null;
      }
      updatedAt_ = null;
      if (updatedAtBuilder_ != null) {
        updatedAtBuilder_.dispose();
        updatedAtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.api.v1.CommonProto.internal_static_api_v1_Contract_descriptor;
    }

    @java.lang.Override
    public com.api.v1.Contract getDefaultInstanceForType() {
      return com.api.v1.Contract.getDefaultInstance();
    }

    @java.lang.Override
    public com.api.v1.Contract build() {
      com.api.v1.Contract result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.api.v1.Contract buildPartial() {
      com.api.v1.Contract result = new com.api.v1.Contract(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.api.v1.Contract result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.status_ = status_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.createdAt_ = createdAtBuilder_ == null
            ? createdAt_
            : createdAtBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.updatedAt_ = updatedAtBuilder_ == null
            ? updatedAt_
            : updatedAtBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.api.v1.Contract) {
        return mergeFrom((com.api.v1.Contract)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.api.v1.Contract other) {
      if (other == com.api.v1.Contract.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.hasCreatedAt()) {
        mergeCreatedAt(other.getCreatedAt());
      }
      if (other.hasUpdatedAt()) {
        mergeUpdatedAt(other.getUpdatedAt());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 162: {
              input.readMessage(
                  internalGetCreatedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 162
            case 170: {
              input.readMessage(
                  internalGetUpdatedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 170
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <pre>
     * Contract ID (e.g. con-1234567890)
     *
     * 契約ID (例: con-1234567890)
     *
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Contract ID (e.g. con-1234567890)
     *
     * 契約ID (例: con-1234567890)
     *
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Contract ID (e.g. con-1234567890)
     *
     * 契約ID (例: con-1234567890)
     *
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Contract ID (e.g. con-1234567890)
     *
     * 契約ID (例: con-1234567890)
     *
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Contract ID (e.g. con-1234567890)
     *
     * 契約ID (例: con-1234567890)
     *
     * &#64;gotags: validate:"required"
     * </pre>
     *
     * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <pre>
     * Status of the contract.
     * </pre>
     *
     * <code>.api.v1.ContractStatus status = 2 [json_name = "status", (.buf.validate.field) = { ... }</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <pre>
     * Status of the contract.
     * </pre>
     *
     * <code>.api.v1.ContractStatus status = 2 [json_name = "status", (.buf.validate.field) = { ... }</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Status of the contract.
     * </pre>
     *
     * <code>.api.v1.ContractStatus status = 2 [json_name = "status", (.buf.validate.field) = { ... }</code>
     * @return The status.
     */
    @java.lang.Override
    public com.api.v1.ContractStatus getStatus() {
      com.api.v1.ContractStatus result = com.api.v1.ContractStatus.forNumber(status_);
      return result == null ? com.api.v1.ContractStatus.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Status of the contract.
     * </pre>
     *
     * <code>.api.v1.ContractStatus status = 2 [json_name = "status", (.buf.validate.field) = { ... }</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(com.api.v1.ContractStatus value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000002;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Status of the contract.
     * </pre>
     *
     * <code>.api.v1.ContractStatus status = 2 [json_name = "status", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000002);
      status_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp createdAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdAtBuilder_;
    /**
     * <pre>
     * Created date of the contract.
     *
     * 契約の作成日時。
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 20 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
     * @return Whether the createdAt field is set.
     */
    public boolean hasCreatedAt() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Created date of the contract.
     *
     * 契約の作成日時。
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 20 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
     * @return The createdAt.
     */
    public com.google.protobuf.Timestamp getCreatedAt() {
      if (createdAtBuilder_ == null) {
        return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      } else {
        return createdAtBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Created date of the contract.
     *
     * 契約の作成日時。
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 20 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
     */
    public Builder setCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createdAt_ = value;
      } else {
        createdAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Created date of the contract.
     *
     * 契約の作成日時。
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 20 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
     */
    public Builder setCreatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createdAtBuilder_ == null) {
        createdAt_ = builderForValue.build();
      } else {
        createdAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Created date of the contract.
     *
     * 契約の作成日時。
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 20 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
     */
    public Builder mergeCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          createdAt_ != null &&
          createdAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getCreatedAtBuilder().mergeFrom(value);
        } else {
          createdAt_ = value;
        }
      } else {
        createdAtBuilder_.mergeFrom(value);
      }
      if (createdAt_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Created date of the contract.
     *
     * 契約の作成日時。
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 20 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
     */
    public Builder clearCreatedAt() {
      bitField0_ = (bitField0_ & ~0x00000004);
      createdAt_ = null;
      if (createdAtBuilder_ != null) {
        createdAtBuilder_.dispose();
        createdAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Created date of the contract.
     *
     * 契約の作成日時。
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 20 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreatedAtBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetCreatedAtFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Created date of the contract.
     *
     * 契約の作成日時。
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 20 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
      if (createdAtBuilder_ != null) {
        return createdAtBuilder_.getMessageOrBuilder();
      } else {
        return createdAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      }
    }
    /**
     * <pre>
     * Created date of the contract.
     *
     * 契約の作成日時。
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 20 [json_name = "createdAt", (.buf.validate.field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetCreatedAtFieldBuilder() {
      if (createdAtBuilder_ == null) {
        createdAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreatedAt(),
                getParentForChildren(),
                isClean());
        createdAt_ = null;
      }
      return createdAtBuilder_;
    }

    private com.google.protobuf.Timestamp updatedAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> updatedAtBuilder_;
    /**
     * <pre>
     * Updated date of the contract.
     *
     * 契約の更新日時。
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updated_at = 21 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
     * @return Whether the updatedAt field is set.
     */
    public boolean hasUpdatedAt() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Updated date of the contract.
     *
     * 契約の更新日時。
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updated_at = 21 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
     * @return The updatedAt.
     */
    public com.google.protobuf.Timestamp getUpdatedAt() {
      if (updatedAtBuilder_ == null) {
        return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
      } else {
        return updatedAtBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Updated date of the contract.
     *
     * 契約の更新日時。
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updated_at = 21 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
     */
    public Builder setUpdatedAt(com.google.protobuf.Timestamp value) {
      if (updatedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        updatedAt_ = value;
      } else {
        updatedAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Updated date of the contract.
     *
     * 契約の更新日時。
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updated_at = 21 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
     */
    public Builder setUpdatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (updatedAtBuilder_ == null) {
        updatedAt_ = builderForValue.build();
      } else {
        updatedAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Updated date of the contract.
     *
     * 契約の更新日時。
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updated_at = 21 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
     */
    public Builder mergeUpdatedAt(com.google.protobuf.Timestamp value) {
      if (updatedAtBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          updatedAt_ != null &&
          updatedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getUpdatedAtBuilder().mergeFrom(value);
        } else {
          updatedAt_ = value;
        }
      } else {
        updatedAtBuilder_.mergeFrom(value);
      }
      if (updatedAt_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Updated date of the contract.
     *
     * 契約の更新日時。
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updated_at = 21 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
     */
    public Builder clearUpdatedAt() {
      bitField0_ = (bitField0_ & ~0x00000008);
      updatedAt_ = null;
      if (updatedAtBuilder_ != null) {
        updatedAtBuilder_.dispose();
        updatedAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Updated date of the contract.
     *
     * 契約の更新日時。
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updated_at = 21 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
     */
    public com.google.protobuf.Timestamp.Builder getUpdatedAtBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return internalGetUpdatedAtFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Updated date of the contract.
     *
     * 契約の更新日時。
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updated_at = 21 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
     */
    public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
      if (updatedAtBuilder_ != null) {
        return updatedAtBuilder_.getMessageOrBuilder();
      } else {
        return updatedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
      }
    }
    /**
     * <pre>
     * Updated date of the contract.
     *
     * 契約の更新日時。
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updated_at = 21 [json_name = "updatedAt", (.buf.validate.field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetUpdatedAtFieldBuilder() {
      if (updatedAtBuilder_ == null) {
        updatedAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getUpdatedAt(),
                getParentForChildren(),
                isClean());
        updatedAt_ = null;
      }
      return updatedAtBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:api.v1.Contract)
  }

  // @@protoc_insertion_point(class_scope:api.v1.Contract)
  private static final com.api.v1.Contract DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.api.v1.Contract();
  }

  public static com.api.v1.Contract getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Contract>
      PARSER = new com.google.protobuf.AbstractParser<Contract>() {
    @java.lang.Override
    public Contract parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Contract> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Contract> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.api.v1.Contract getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

