// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/payment.proto
// Protobuf Java Version: 4.34.0

package com.api.v1;

@com.google.protobuf.Generated
public interface CreateContractWithoutChargeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.v1.CreateContractWithoutChargeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Buyer information for the new contract
   * Contains details about the entity entering into the contract
   * including name, contact information, etc.
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>.api.v1.Buyer buyer = 1 [json_name = "buyer", (.buf.validate.field) = { ... }</code>
   * @return Whether the buyer field is set.
   */
  boolean hasBuyer();
  /**
   * <pre>
   * Buyer information for the new contract
   * Contains details about the entity entering into the contract
   * including name, contact information, etc.
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>.api.v1.Buyer buyer = 1 [json_name = "buyer", (.buf.validate.field) = { ... }</code>
   * @return The buyer.
   */
  com.api.v1.Buyer getBuyer();
  /**
   * <pre>
   * Buyer information for the new contract
   * Contains details about the entity entering into the contract
   * including name, contact information, etc.
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>.api.v1.Buyer buyer = 1 [json_name = "buyer", (.buf.validate.field) = { ... }</code>
   */
  com.api.v1.BuyerOrBuilder getBuyerOrBuilder();

  /**
   * <pre>
   * Redirect URL to send the customer after contract creation
   * This URL is used in the checkout flow to redirect the customer
   * after they complete the contract creation process
   * </pre>
   *
   * <code>optional .api.v1.URL redirect = 10 [json_name = "redirect"];</code>
   * @return Whether the redirect field is set.
   */
  boolean hasRedirect();
  /**
   * <pre>
   * Redirect URL to send the customer after contract creation
   * This URL is used in the checkout flow to redirect the customer
   * after they complete the contract creation process
   * </pre>
   *
   * <code>optional .api.v1.URL redirect = 10 [json_name = "redirect"];</code>
   * @return The redirect.
   */
  com.api.v1.URL getRedirect();
  /**
   * <pre>
   * Redirect URL to send the customer after contract creation
   * This URL is used in the checkout flow to redirect the customer
   * after they complete the contract creation process
   * </pre>
   *
   * <code>optional .api.v1.URL redirect = 10 [json_name = "redirect"];</code>
   */
  com.api.v1.URLOrBuilder getRedirectOrBuilder();
}
