// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/payment.proto
// Protobuf Java Version: 4.34.1

package com.api.v1;

@com.google.protobuf.Generated
public interface CreateContractWithoutChargeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.v1.CreateContractWithoutChargeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The newly created contract
   * Contains contract ID, status, creation timestamp, etc.
   * This is the primary object created by this operation
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>.api.v1.Contract contract = 1 [json_name = "contract", (.buf.validate.field) = { ... }</code>
   * @return Whether the contract field is set.
   */
  boolean hasContract();
  /**
   * <pre>
   * The newly created contract
   * Contains contract ID, status, creation timestamp, etc.
   * This is the primary object created by this operation
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>.api.v1.Contract contract = 1 [json_name = "contract", (.buf.validate.field) = { ... }</code>
   * @return The contract.
   */
  com.api.v1.Contract getContract();
  /**
   * <pre>
   * The newly created contract
   * Contains contract ID, status, creation timestamp, etc.
   * This is the primary object created by this operation
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>.api.v1.Contract contract = 1 [json_name = "contract", (.buf.validate.field) = { ... }</code>
   */
  com.api.v1.ContractOrBuilder getContractOrBuilder();

  /**
   * <pre>
   * Customer information associated with this contract
   * Contains customer details that were created or associated
   * during the contract creation process
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>.api.v1.Customer customer = 2 [json_name = "customer", (.buf.validate.field) = { ... }</code>
   * @return Whether the customer field is set.
   */
  boolean hasCustomer();
  /**
   * <pre>
   * Customer information associated with this contract
   * Contains customer details that were created or associated
   * during the contract creation process
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>.api.v1.Customer customer = 2 [json_name = "customer", (.buf.validate.field) = { ... }</code>
   * @return The customer.
   */
  com.api.v1.Customer getCustomer();
  /**
   * <pre>
   * Customer information associated with this contract
   * Contains customer details that were created or associated
   * during the contract creation process
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>.api.v1.Customer customer = 2 [json_name = "customer", (.buf.validate.field) = { ... }</code>
   */
  com.api.v1.CustomerOrBuilder getCustomerOrBuilder();

  /**
   * <pre>
   * Payment link information related to this contract
   * Even though no charge is created initially, this link provides
   * access to manage the contract
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>.api.v1.PaymentLink payment_link = 3 [json_name = "paymentLink", (.buf.validate.field) = { ... }</code>
   * @return Whether the paymentLink field is set.
   */
  boolean hasPaymentLink();
  /**
   * <pre>
   * Payment link information related to this contract
   * Even though no charge is created initially, this link provides
   * access to manage the contract
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>.api.v1.PaymentLink payment_link = 3 [json_name = "paymentLink", (.buf.validate.field) = { ... }</code>
   * @return The paymentLink.
   */
  com.api.v1.PaymentLink getPaymentLink();
  /**
   * <pre>
   * Payment link information related to this contract
   * Even though no charge is created initially, this link provides
   * access to manage the contract
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>.api.v1.PaymentLink payment_link = 3 [json_name = "paymentLink", (.buf.validate.field) = { ... }</code>
   */
  com.api.v1.PaymentLinkOrBuilder getPaymentLinkOrBuilder();
}
