// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/merchant_webhooks.proto
// Protobuf Java Version: 4.34.0

package com.api.v1;

@com.google.protobuf.Generated
public interface ErrorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.v1.ErrorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.error.v1.ErrorType error_type = 1 [json_name = "errorType", (.buf.validate.field) = { ... }</code>
   * @return The enum numeric value on the wire for errorType.
   */
  int getErrorTypeValue();
  /**
   * <code>.error.v1.ErrorType error_type = 1 [json_name = "errorType", (.buf.validate.field) = { ... }</code>
   * @return The errorType.
   */
  com.error.v1.ErrorType getErrorType();
}
