// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/bank.proto
// Protobuf Java Version: 4.34.0

package com.api.v1;

/**
 * Protobuf type {@code api.v1.GetBankResponse}
 */
@com.google.protobuf.Generated
public final class GetBankResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:api.v1.GetBankResponse)
    GetBankResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "GetBankResponse");
  }
  // Use GetBankResponse.newBuilder() to construct.
  private GetBankResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetBankResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.api.v1.BankProto.internal_static_api_v1_GetBankResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.api.v1.BankProto.internal_static_api_v1_GetBankResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.api.v1.BankProto.internal_static_api_v1_GetBankResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.api.v1.GetBankResponse.class, com.api.v1.GetBankResponse.Builder.class);
  }

  private int bitField0_;
  public static final int BANK_FIELD_NUMBER = 1;
  private com.api.v1.Bank bank_;
  /**
   * <code>.api.v1.Bank bank = 1 [json_name = "bank", (.buf.validate.field) = { ... }</code>
   * @return Whether the bank field is set.
   */
  @java.lang.Override
  public boolean hasBank() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.api.v1.Bank bank = 1 [json_name = "bank", (.buf.validate.field) = { ... }</code>
   * @return The bank.
   */
  @java.lang.Override
  public com.api.v1.Bank getBank() {
    return bank_ == null ? com.api.v1.Bank.getDefaultInstance() : bank_;
  }
  /**
   * <code>.api.v1.Bank bank = 1 [json_name = "bank", (.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public com.api.v1.BankOrBuilder getBankOrBuilder() {
    return bank_ == null ? com.api.v1.Bank.getDefaultInstance() : bank_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getBank());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBank());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.api.v1.GetBankResponse)) {
      return super.equals(obj);
    }
    com.api.v1.GetBankResponse other = (com.api.v1.GetBankResponse) obj;

    if (hasBank() != other.hasBank()) return false;
    if (hasBank()) {
      if (!getBank()
          .equals(other.getBank())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBank()) {
      hash = (37 * hash) + BANK_FIELD_NUMBER;
      hash = (53 * hash) + getBank().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.api.v1.GetBankResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.api.v1.GetBankResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.api.v1.GetBankResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.api.v1.GetBankResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.api.v1.GetBankResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.api.v1.GetBankResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.api.v1.GetBankResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.api.v1.GetBankResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.api.v1.GetBankResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.api.v1.GetBankResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.api.v1.GetBankResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.api.v1.GetBankResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.api.v1.GetBankResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code api.v1.GetBankResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.v1.GetBankResponse)
      com.api.v1.GetBankResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.api.v1.BankProto.internal_static_api_v1_GetBankResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.api.v1.BankProto.internal_static_api_v1_GetBankResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.api.v1.GetBankResponse.class, com.api.v1.GetBankResponse.Builder.class);
    }

    // Construct using com.api.v1.GetBankResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetBankFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      bank_ = null;
      if (bankBuilder_ != null) {
        bankBuilder_.dispose();
        bankBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.api.v1.BankProto.internal_static_api_v1_GetBankResponse_descriptor;
    }

    @java.lang.Override
    public com.api.v1.GetBankResponse getDefaultInstanceForType() {
      return com.api.v1.GetBankResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.api.v1.GetBankResponse build() {
      com.api.v1.GetBankResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.api.v1.GetBankResponse buildPartial() {
      com.api.v1.GetBankResponse result = new com.api.v1.GetBankResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.api.v1.GetBankResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.bank_ = bankBuilder_ == null
            ? bank_
            : bankBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.api.v1.GetBankResponse) {
        return mergeFrom((com.api.v1.GetBankResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.api.v1.GetBankResponse other) {
      if (other == com.api.v1.GetBankResponse.getDefaultInstance()) return this;
      if (other.hasBank()) {
        mergeBank(other.getBank());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetBankFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.api.v1.Bank bank_;
    private com.google.protobuf.SingleFieldBuilder<
        com.api.v1.Bank, com.api.v1.Bank.Builder, com.api.v1.BankOrBuilder> bankBuilder_;
    /**
     * <code>.api.v1.Bank bank = 1 [json_name = "bank", (.buf.validate.field) = { ... }</code>
     * @return Whether the bank field is set.
     */
    public boolean hasBank() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.api.v1.Bank bank = 1 [json_name = "bank", (.buf.validate.field) = { ... }</code>
     * @return The bank.
     */
    public com.api.v1.Bank getBank() {
      if (bankBuilder_ == null) {
        return bank_ == null ? com.api.v1.Bank.getDefaultInstance() : bank_;
      } else {
        return bankBuilder_.getMessage();
      }
    }
    /**
     * <code>.api.v1.Bank bank = 1 [json_name = "bank", (.buf.validate.field) = { ... }</code>
     */
    public Builder setBank(com.api.v1.Bank value) {
      if (bankBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bank_ = value;
      } else {
        bankBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.api.v1.Bank bank = 1 [json_name = "bank", (.buf.validate.field) = { ... }</code>
     */
    public Builder setBank(
        com.api.v1.Bank.Builder builderForValue) {
      if (bankBuilder_ == null) {
        bank_ = builderForValue.build();
      } else {
        bankBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.api.v1.Bank bank = 1 [json_name = "bank", (.buf.validate.field) = { ... }</code>
     */
    public Builder mergeBank(com.api.v1.Bank value) {
      if (bankBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          bank_ != null &&
          bank_ != com.api.v1.Bank.getDefaultInstance()) {
          getBankBuilder().mergeFrom(value);
        } else {
          bank_ = value;
        }
      } else {
        bankBuilder_.mergeFrom(value);
      }
      if (bank_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.api.v1.Bank bank = 1 [json_name = "bank", (.buf.validate.field) = { ... }</code>
     */
    public Builder clearBank() {
      bitField0_ = (bitField0_ & ~0x00000001);
      bank_ = null;
      if (bankBuilder_ != null) {
        bankBuilder_.dispose();
        bankBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.api.v1.Bank bank = 1 [json_name = "bank", (.buf.validate.field) = { ... }</code>
     */
    public com.api.v1.Bank.Builder getBankBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetBankFieldBuilder().getBuilder();
    }
    /**
     * <code>.api.v1.Bank bank = 1 [json_name = "bank", (.buf.validate.field) = { ... }</code>
     */
    public com.api.v1.BankOrBuilder getBankOrBuilder() {
      if (bankBuilder_ != null) {
        return bankBuilder_.getMessageOrBuilder();
      } else {
        return bank_ == null ?
            com.api.v1.Bank.getDefaultInstance() : bank_;
      }
    }
    /**
     * <code>.api.v1.Bank bank = 1 [json_name = "bank", (.buf.validate.field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.api.v1.Bank, com.api.v1.Bank.Builder, com.api.v1.BankOrBuilder> 
        internalGetBankFieldBuilder() {
      if (bankBuilder_ == null) {
        bankBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.api.v1.Bank, com.api.v1.Bank.Builder, com.api.v1.BankOrBuilder>(
                getBank(),
                getParentForChildren(),
                isClean());
        bank_ = null;
      }
      return bankBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:api.v1.GetBankResponse)
  }

  // @@protoc_insertion_point(class_scope:api.v1.GetBankResponse)
  private static final com.api.v1.GetBankResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.api.v1.GetBankResponse();
  }

  public static com.api.v1.GetBankResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetBankResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetBankResponse>() {
    @java.lang.Override
    public GetBankResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetBankResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetBankResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.api.v1.GetBankResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

