// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/bank.proto
// Protobuf Java Version: 4.33.5

package com.api.v1;

@com.google.protobuf.Generated
public interface GetBranchesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.v1.GetBranchesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .api.v1.BankBranch branches = 1 [json_name = "branches"];</code>
   */
  java.util.List<com.api.v1.BankBranch> 
      getBranchesList();
  /**
   * <code>repeated .api.v1.BankBranch branches = 1 [json_name = "branches"];</code>
   */
  com.api.v1.BankBranch getBranches(int index);
  /**
   * <code>repeated .api.v1.BankBranch branches = 1 [json_name = "branches"];</code>
   */
  int getBranchesCount();
  /**
   * <code>repeated .api.v1.BankBranch branches = 1 [json_name = "branches"];</code>
   */
  java.util.List<? extends com.api.v1.BankBranchOrBuilder> 
      getBranchesOrBuilderList();
  /**
   * <code>repeated .api.v1.BankBranch branches = 1 [json_name = "branches"];</code>
   */
  com.api.v1.BankBranchOrBuilder getBranchesOrBuilder(
      int index);
}
