// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/payment.proto
// Protobuf Java Version: 4.34.0

package com.api.v1;

@com.google.protobuf.Generated
public interface GetChargesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.v1.GetChargesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>string customer = 1 [json_name = "customer", (.buf.validate.field) = { ... }</code>
   * @return The customer.
   */
  java.lang.String getCustomer();
  /**
   * <pre>
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>string customer = 1 [json_name = "customer", (.buf.validate.field) = { ... }</code>
   * @return The bytes for customer.
   */
  com.google.protobuf.ByteString
      getCustomerBytes();

  /**
   * <code>optional .api.v1.Pagination pagination = 2 [json_name = "pagination"];</code>
   * @return Whether the pagination field is set.
   */
  boolean hasPagination();
  /**
   * <code>optional .api.v1.Pagination pagination = 2 [json_name = "pagination"];</code>
   * @return The pagination.
   */
  com.api.v1.Pagination getPagination();
  /**
   * <code>optional .api.v1.Pagination pagination = 2 [json_name = "pagination"];</code>
   */
  com.api.v1.PaginationOrBuilder getPaginationOrBuilder();
}
