// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/customer.proto
// Protobuf Java Version: 4.34.0

package com.api.v1;

/**
 * Protobuf type {@code api.v1.GetContractResponse}
 */
@com.google.protobuf.Generated
public final class GetContractResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:api.v1.GetContractResponse)
    GetContractResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "GetContractResponse");
  }
  // Use GetContractResponse.newBuilder() to construct.
  private GetContractResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetContractResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.api.v1.CustomerProto.internal_static_api_v1_GetContractResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.api.v1.CustomerProto.internal_static_api_v1_GetContractResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.api.v1.CustomerProto.internal_static_api_v1_GetContractResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.api.v1.GetContractResponse.class, com.api.v1.GetContractResponse.Builder.class);
  }

  private int bitField0_;
  public static final int CUSTOMER_FIELD_NUMBER = 1;
  private com.api.v1.MerchantCustomer customer_;
  /**
   * <code>.api.v1.MerchantCustomer customer = 1 [json_name = "customer", (.buf.validate.field) = { ... }</code>
   * @return Whether the customer field is set.
   */
  @java.lang.Override
  public boolean hasCustomer() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.api.v1.MerchantCustomer customer = 1 [json_name = "customer", (.buf.validate.field) = { ... }</code>
   * @return The customer.
   */
  @java.lang.Override
  public com.api.v1.MerchantCustomer getCustomer() {
    return customer_ == null ? com.api.v1.MerchantCustomer.getDefaultInstance() : customer_;
  }
  /**
   * <code>.api.v1.MerchantCustomer customer = 1 [json_name = "customer", (.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public com.api.v1.MerchantCustomerOrBuilder getCustomerOrBuilder() {
    return customer_ == null ? com.api.v1.MerchantCustomer.getDefaultInstance() : customer_;
  }

  public static final int CONTRACT_FIELD_NUMBER = 2;
  private com.api.v1.Contract contract_;
  /**
   * <code>.api.v1.Contract contract = 2 [json_name = "contract", (.buf.validate.field) = { ... }</code>
   * @return Whether the contract field is set.
   */
  @java.lang.Override
  public boolean hasContract() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.api.v1.Contract contract = 2 [json_name = "contract", (.buf.validate.field) = { ... }</code>
   * @return The contract.
   */
  @java.lang.Override
  public com.api.v1.Contract getContract() {
    return contract_ == null ? com.api.v1.Contract.getDefaultInstance() : contract_;
  }
  /**
   * <code>.api.v1.Contract contract = 2 [json_name = "contract", (.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public com.api.v1.ContractOrBuilder getContractOrBuilder() {
    return contract_ == null ? com.api.v1.Contract.getDefaultInstance() : contract_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getCustomer());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getContract());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCustomer());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getContract());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.api.v1.GetContractResponse)) {
      return super.equals(obj);
    }
    com.api.v1.GetContractResponse other = (com.api.v1.GetContractResponse) obj;

    if (hasCustomer() != other.hasCustomer()) return false;
    if (hasCustomer()) {
      if (!getCustomer()
          .equals(other.getCustomer())) return false;
    }
    if (hasContract() != other.hasContract()) return false;
    if (hasContract()) {
      if (!getContract()
          .equals(other.getContract())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCustomer()) {
      hash = (37 * hash) + CUSTOMER_FIELD_NUMBER;
      hash = (53 * hash) + getCustomer().hashCode();
    }
    if (hasContract()) {
      hash = (37 * hash) + CONTRACT_FIELD_NUMBER;
      hash = (53 * hash) + getContract().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.api.v1.GetContractResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.api.v1.GetContractResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.api.v1.GetContractResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.api.v1.GetContractResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.api.v1.GetContractResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.api.v1.GetContractResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.api.v1.GetContractResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.api.v1.GetContractResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.api.v1.GetContractResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.api.v1.GetContractResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.api.v1.GetContractResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.api.v1.GetContractResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.api.v1.GetContractResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code api.v1.GetContractResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.v1.GetContractResponse)
      com.api.v1.GetContractResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.api.v1.CustomerProto.internal_static_api_v1_GetContractResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.api.v1.CustomerProto.internal_static_api_v1_GetContractResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.api.v1.GetContractResponse.class, com.api.v1.GetContractResponse.Builder.class);
    }

    // Construct using com.api.v1.GetContractResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetCustomerFieldBuilder();
        internalGetContractFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      customer_ = null;
      if (customerBuilder_ != null) {
        customerBuilder_.dispose();
        customerBuilder_ = null;
      }
      contract_ = null;
      if (contractBuilder_ != null) {
        contractBuilder_.dispose();
        contractBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.api.v1.CustomerProto.internal_static_api_v1_GetContractResponse_descriptor;
    }

    @java.lang.Override
    public com.api.v1.GetContractResponse getDefaultInstanceForType() {
      return com.api.v1.GetContractResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.api.v1.GetContractResponse build() {
      com.api.v1.GetContractResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.api.v1.GetContractResponse buildPartial() {
      com.api.v1.GetContractResponse result = new com.api.v1.GetContractResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.api.v1.GetContractResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.customer_ = customerBuilder_ == null
            ? customer_
            : customerBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.contract_ = contractBuilder_ == null
            ? contract_
            : contractBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.api.v1.GetContractResponse) {
        return mergeFrom((com.api.v1.GetContractResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.api.v1.GetContractResponse other) {
      if (other == com.api.v1.GetContractResponse.getDefaultInstance()) return this;
      if (other.hasCustomer()) {
        mergeCustomer(other.getCustomer());
      }
      if (other.hasContract()) {
        mergeContract(other.getContract());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetCustomerFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetContractFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.api.v1.MerchantCustomer customer_;
    private com.google.protobuf.SingleFieldBuilder<
        com.api.v1.MerchantCustomer, com.api.v1.MerchantCustomer.Builder, com.api.v1.MerchantCustomerOrBuilder> customerBuilder_;
    /**
     * <code>.api.v1.MerchantCustomer customer = 1 [json_name = "customer", (.buf.validate.field) = { ... }</code>
     * @return Whether the customer field is set.
     */
    public boolean hasCustomer() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.api.v1.MerchantCustomer customer = 1 [json_name = "customer", (.buf.validate.field) = { ... }</code>
     * @return The customer.
     */
    public com.api.v1.MerchantCustomer getCustomer() {
      if (customerBuilder_ == null) {
        return customer_ == null ? com.api.v1.MerchantCustomer.getDefaultInstance() : customer_;
      } else {
        return customerBuilder_.getMessage();
      }
    }
    /**
     * <code>.api.v1.MerchantCustomer customer = 1 [json_name = "customer", (.buf.validate.field) = { ... }</code>
     */
    public Builder setCustomer(com.api.v1.MerchantCustomer value) {
      if (customerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        customer_ = value;
      } else {
        customerBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.api.v1.MerchantCustomer customer = 1 [json_name = "customer", (.buf.validate.field) = { ... }</code>
     */
    public Builder setCustomer(
        com.api.v1.MerchantCustomer.Builder builderForValue) {
      if (customerBuilder_ == null) {
        customer_ = builderForValue.build();
      } else {
        customerBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.api.v1.MerchantCustomer customer = 1 [json_name = "customer", (.buf.validate.field) = { ... }</code>
     */
    public Builder mergeCustomer(com.api.v1.MerchantCustomer value) {
      if (customerBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          customer_ != null &&
          customer_ != com.api.v1.MerchantCustomer.getDefaultInstance()) {
          getCustomerBuilder().mergeFrom(value);
        } else {
          customer_ = value;
        }
      } else {
        customerBuilder_.mergeFrom(value);
      }
      if (customer_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.api.v1.MerchantCustomer customer = 1 [json_name = "customer", (.buf.validate.field) = { ... }</code>
     */
    public Builder clearCustomer() {
      bitField0_ = (bitField0_ & ~0x00000001);
      customer_ = null;
      if (customerBuilder_ != null) {
        customerBuilder_.dispose();
        customerBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.api.v1.MerchantCustomer customer = 1 [json_name = "customer", (.buf.validate.field) = { ... }</code>
     */
    public com.api.v1.MerchantCustomer.Builder getCustomerBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetCustomerFieldBuilder().getBuilder();
    }
    /**
     * <code>.api.v1.MerchantCustomer customer = 1 [json_name = "customer", (.buf.validate.field) = { ... }</code>
     */
    public com.api.v1.MerchantCustomerOrBuilder getCustomerOrBuilder() {
      if (customerBuilder_ != null) {
        return customerBuilder_.getMessageOrBuilder();
      } else {
        return customer_ == null ?
            com.api.v1.MerchantCustomer.getDefaultInstance() : customer_;
      }
    }
    /**
     * <code>.api.v1.MerchantCustomer customer = 1 [json_name = "customer", (.buf.validate.field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.api.v1.MerchantCustomer, com.api.v1.MerchantCustomer.Builder, com.api.v1.MerchantCustomerOrBuilder> 
        internalGetCustomerFieldBuilder() {
      if (customerBuilder_ == null) {
        customerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.api.v1.MerchantCustomer, com.api.v1.MerchantCustomer.Builder, com.api.v1.MerchantCustomerOrBuilder>(
                getCustomer(),
                getParentForChildren(),
                isClean());
        customer_ = null;
      }
      return customerBuilder_;
    }

    private com.api.v1.Contract contract_;
    private com.google.protobuf.SingleFieldBuilder<
        com.api.v1.Contract, com.api.v1.Contract.Builder, com.api.v1.ContractOrBuilder> contractBuilder_;
    /**
     * <code>.api.v1.Contract contract = 2 [json_name = "contract", (.buf.validate.field) = { ... }</code>
     * @return Whether the contract field is set.
     */
    public boolean hasContract() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.api.v1.Contract contract = 2 [json_name = "contract", (.buf.validate.field) = { ... }</code>
     * @return The contract.
     */
    public com.api.v1.Contract getContract() {
      if (contractBuilder_ == null) {
        return contract_ == null ? com.api.v1.Contract.getDefaultInstance() : contract_;
      } else {
        return contractBuilder_.getMessage();
      }
    }
    /**
     * <code>.api.v1.Contract contract = 2 [json_name = "contract", (.buf.validate.field) = { ... }</code>
     */
    public Builder setContract(com.api.v1.Contract value) {
      if (contractBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        contract_ = value;
      } else {
        contractBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.api.v1.Contract contract = 2 [json_name = "contract", (.buf.validate.field) = { ... }</code>
     */
    public Builder setContract(
        com.api.v1.Contract.Builder builderForValue) {
      if (contractBuilder_ == null) {
        contract_ = builderForValue.build();
      } else {
        contractBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.api.v1.Contract contract = 2 [json_name = "contract", (.buf.validate.field) = { ... }</code>
     */
    public Builder mergeContract(com.api.v1.Contract value) {
      if (contractBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          contract_ != null &&
          contract_ != com.api.v1.Contract.getDefaultInstance()) {
          getContractBuilder().mergeFrom(value);
        } else {
          contract_ = value;
        }
      } else {
        contractBuilder_.mergeFrom(value);
      }
      if (contract_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.api.v1.Contract contract = 2 [json_name = "contract", (.buf.validate.field) = { ... }</code>
     */
    public Builder clearContract() {
      bitField0_ = (bitField0_ & ~0x00000002);
      contract_ = null;
      if (contractBuilder_ != null) {
        contractBuilder_.dispose();
        contractBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.api.v1.Contract contract = 2 [json_name = "contract", (.buf.validate.field) = { ... }</code>
     */
    public com.api.v1.Contract.Builder getContractBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetContractFieldBuilder().getBuilder();
    }
    /**
     * <code>.api.v1.Contract contract = 2 [json_name = "contract", (.buf.validate.field) = { ... }</code>
     */
    public com.api.v1.ContractOrBuilder getContractOrBuilder() {
      if (contractBuilder_ != null) {
        return contractBuilder_.getMessageOrBuilder();
      } else {
        return contract_ == null ?
            com.api.v1.Contract.getDefaultInstance() : contract_;
      }
    }
    /**
     * <code>.api.v1.Contract contract = 2 [json_name = "contract", (.buf.validate.field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.api.v1.Contract, com.api.v1.Contract.Builder, com.api.v1.ContractOrBuilder> 
        internalGetContractFieldBuilder() {
      if (contractBuilder_ == null) {
        contractBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.api.v1.Contract, com.api.v1.Contract.Builder, com.api.v1.ContractOrBuilder>(
                getContract(),
                getParentForChildren(),
                isClean());
        contract_ = null;
      }
      return contractBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:api.v1.GetContractResponse)
  }

  // @@protoc_insertion_point(class_scope:api.v1.GetContractResponse)
  private static final com.api.v1.GetContractResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.api.v1.GetContractResponse();
  }

  public static com.api.v1.GetContractResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetContractResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetContractResponse>() {
    @java.lang.Override
    public GetContractResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetContractResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetContractResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.api.v1.GetContractResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

