// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/healthcheck.proto
// Protobuf Java Version: 4.34.1

package com.api.v1;

@com.google.protobuf.Generated
public final class HealthcheckProto extends com.google.protobuf.GeneratedFile {
  private HealthcheckProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "HealthcheckProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_PingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_PingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_PingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_PingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030api/v1/healthcheck.proto\022\006api.v1\"\r\n\013Pi" +
      "ngRequest\"\036\n\014PingResponse\022\016\n\002ok\030\001 \001(\010R\002o" +
      "k2I\n\022HealthcheckService\0223\n\004Ping\022\023.api.v1" +
      ".PingRequest\032\024.api.v1.PingResponse\"\000Bt\n\n" +
      "com.api.v1B\020HealthcheckProtoP\001Z\033api/prot" +
      "o/gen/api/v1;api_v1\242\002\003AXX\252\002\006Api.V1\312\002\006Api" +
      "\\V1\342\002\022Api\\V1\\GPBMetadata\352\002\007Api::V1b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_api_v1_PingRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_api_v1_PingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_PingRequest_descriptor,
        new java.lang.String[] { });
    internal_static_api_v1_PingResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_api_v1_PingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_PingResponse_descriptor,
        new java.lang.String[] { "Ok", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
