// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/common.proto
// Protobuf Java Version: 4.34.0

package com.api.v1;

@com.google.protobuf.Generated
public interface MerchantCustomerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.v1.MerchantCustomer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.api.v1.Customer customer = 1 [json_name = "customer", (.buf.validate.field) = { ... }</code>
   * @return Whether the customer field is set.
   */
  boolean hasCustomer();
  /**
   * <code>.api.v1.Customer customer = 1 [json_name = "customer", (.buf.validate.field) = { ... }</code>
   * @return The customer.
   */
  com.api.v1.Customer getCustomer();
  /**
   * <code>.api.v1.Customer customer = 1 [json_name = "customer", (.buf.validate.field) = { ... }</code>
   */
  com.api.v1.CustomerOrBuilder getCustomerOrBuilder();

  /**
   * <code>.api.v1.Merchant merchant = 2 [json_name = "merchant", (.buf.validate.field) = { ... }</code>
   * @return Whether the merchant field is set.
   */
  boolean hasMerchant();
  /**
   * <code>.api.v1.Merchant merchant = 2 [json_name = "merchant", (.buf.validate.field) = { ... }</code>
   * @return The merchant.
   */
  com.api.v1.Merchant getMerchant();
  /**
   * <code>.api.v1.Merchant merchant = 2 [json_name = "merchant", (.buf.validate.field) = { ... }</code>
   */
  com.api.v1.MerchantOrBuilder getMerchantOrBuilder();
}
