// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/merchant_webhooks.proto
// Protobuf Java Version: 4.34.0

package com.api.v1;

@com.google.protobuf.Generated
public final class MerchantWebhooksProto extends com.google.protobuf.GeneratedFile {
  private MerchantWebhooksProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "MerchantWebhooksProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_ErrorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_ErrorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_ErrorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_ErrorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_MessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_MessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_MessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_MessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_MerchantWebhookMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_MerchantWebhookMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_ChargeMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_ChargeMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_ContractMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_ContractMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_UserAccountMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_UserAccountMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_Error_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_Error_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_ErrorDetail_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_ErrorDetail_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036api/v1/merchant_webhooks.proto\022\006api.v1" +
      "\032\033buf/validate/validate.proto\032\024error/v1/" +
      "error.proto\032\034google/api/annotations.prot" +
      "o\032\031google/protobuf/any.proto\032\037google/pro" +
      "tobuf/timestamp.proto\"\016\n\014ErrorRequest\"K\n" +
      "\rErrorResponse\022:\n\nerror_type\030\001 \001(\0162\023.err" +
      "or.v1.ErrorTypeB\006\272H\003\310\001\001R\terrorType\"\020\n\016Me" +
      "ssageRequest\"\333\002\n\017MessageResponse\022`\n\030merc" +
      "hant_webhook_message\030\001 \001(\0132\036.api.v1.Merc" +
      "hantWebhookMessageB\006\272H\003\310\001\001R\026merchantWebh" +
      "ookMessage\022D\n\016charge_message\030\002 \001(\0132\025.api" +
      ".v1.ChargeMessageB\006\272H\003\310\001\001R\rchargeMessage" +
      "\022J\n\020contract_message\030\003 \001(\0132\027.api.v1.Cont" +
      "ractMessageB\006\272H\003\310\001\001R\017contractMessage\022T\n\024" +
      "user_account_message\030\004 \001(\0132\032.api.v1.User" +
      "AccountMessageB\006\272H\003\310\001\001R\022userAccountMessa" +
      "ge\"\214\002\n\026MerchantWebhookMessage\022\026\n\002id\030\001 \001(" +
      "\tB\006\272H\003\310\001\001R\002id\022$\n\tsignature\030\002 \001(\tB\006\272H\003\310\001\001" +
      "R\tsignature\0228\n\nevent_type\030\004 \001(\0162\021.api.v1" +
      ".EventTypeB\006\272H\003\310\001\001R\teventType\0226\n\007content" +
      "\030\005 \001(\0132\024.google.protobuf.AnyB\006\272H\003\310\001\001R\007co" +
      "ntent\022B\n\ncreated_at\030\347\007 \001(\0132\032.google.prot" +
      "obuf.TimestampB\006\272H\003\310\001\001R\tcreatedAt\"\323\006\n\rCh" +
      "argeMessage\022\"\n\002id\030\001 \001(\tB\022\272H\017r\n2\010^trx-.*$" +
      "\310\001\001R\002id\022.\n\010customer\030\002 \001(\tB\022\272H\017r\n2\010^cus-." +
      "*$\310\001\001R\010customer\022<\n\006status\030\003 \001(\0162\034.api.v1" +
      ".ChargeMessage.StatusB\006\272H\003\310\001\001R\006status\022(\n" +
      "\013description\030\004 \001(\tB\006\272H\003\310\001\001R\013description\022" +
      "+\n\rmerchant_name\030\005 \001(\tB\006\272H\003\310\001\001R\014merchant" +
      "Name\022-\n\016initial_amount\030\006 \001(\005B\006\272H\003\310\001\001R\rin" +
      "itialAmount\022\"\n\010discount\030\007 \001(\005B\006\272H\003\310\001\001R\010d" +
      "iscount\022)\n\014final_amount\030\010 \001(\005B\006\272H\003\310\001\001R\013f" +
      "inalAmount\022,\n\017amount_refunded\030\t \001(\005H\000R\016a" +
      "mountRefunded\210\001\001\022\"\n\010currency\030\n \001(\tB\006\272H\003\310" +
      "\001\001R\010currency\022&\n\014processed_at\030\013 \001(\tH\001R\013pr" +
      "ocessedAt\210\001\001\022\036\n\010jamm_fee\030\014 \001(\005H\002R\007jammFe" +
      "e\210\001\001\022%\n\ncreated_at\030\r \001(\tB\006\272H\003\310\001\001R\tcreate" +
      "dAt\022%\n\nupdated_at\030\016 \001(\tB\006\272H\003\310\001\001R\tupdated" +
      "At\022(\n\005error\030\024 \001(\0132\r.api.v1.ErrorH\003R\005erro" +
      "r\210\001\001\"\214\001\n\006Status\022\026\n\022STATUS_UNSPECIFIED\020\000\022" +
      "\022\n\016STATUS_SUCCESS\020\001\022\022\n\016STATUS_FAILURE\020\002\022" +
      "\027\n\023STATUS_WAITING_EKYC\020\003\022\023\n\017STATUS_BLOCK" +
      "ING\020\004\022\024\n\020STATUS_CANCELLED\020\005B\022\n\020_amount_r" +
      "efundedB\017\n\r_processed_atB\013\n\t_jamm_feeB\010\n" +
      "\006_error\"\300\001\n\017ContractMessage\022.\n\010customer\030" +
      "\001 \001(\tB\022\272H\017r\n2\010^cus-.*$\310\001\001R\010customer\022%\n\nc" +
      "reated_at\030\002 \001(\tB\006\272H\003\310\001\001R\tcreatedAt\022)\n\014ac" +
      "tivated_at\030\003 \001(\tB\006\272H\003\310\001\001R\013activatedAt\022+\n" +
      "\rmerchant_name\030\004 \001(\tB\006\272H\003\310\001\001R\014merchantNa" +
      "me\"\266\001\n\022UserAccountMessage\022.\n\010customer\030\001 " +
      "\001(\tB\022\272H\017r\n2\010^cus-.*$\310\001\001R\010customer\022\034\n\005ema" +
      "il\030\002 \001(\tB\006\272H\003\310\001\001R\005email\022%\n\ndeleted_at\030\003 " +
      "\001(\tB\006\272H\003\310\001\001R\tdeletedAt\022+\n\rmerchant_name\030" +
      "\004 \001(\tB\006\272H\003\310\001\001R\014merchantName\"~\n\005Error\022\032\n\004" +
      "code\030\001 \001(\tB\006\272H\003\310\001\001R\004code\022 \n\007message\030\002 \001(" +
      "\tB\006\272H\003\310\001\001R\007message\0227\n\007details\030\003 \003(\0132\023.ap" +
      "i.v1.ErrorDetailB\010\272H\005\222\001\002\010\001R\007details\"]\n\013E" +
      "rrorDetail\022\032\n\004type\030\001 \001(\tB\006\272H\003\310\001\001R\004type\022\034" +
      "\n\005value\030\002 \001(\tB\006\272H\003\310\001\001R\005value\022\024\n\005debug\030\003 " +
      "\001(\tR\005debug*\236\002\n\tEventType\022\032\n\026EVENT_TYPE_U" +
      "NSPECIFIED\020\000\022\035\n\031EVENT_TYPE_CHARGE_CREATE" +
      "D\020\003\022\035\n\031EVENT_TYPE_CHARGE_UPDATED\020\004\022\035\n\031EV" +
      "ENT_TYPE_CHARGE_SUCCESS\020\005\022\032\n\026EVENT_TYPE_" +
      "CHARGE_FAIL\020\006\022\034\n\030EVENT_TYPE_CHARGE_REFUN" +
      "D\020\007\022!\n\035EVENT_TYPE_CONTRACT_ACTIVATED\020\024\022#" +
      "\n\037EVENT_TYPE_USER_ACCOUNT_DELETED\020\036\022\026\n\022E" +
      "VENT_TYPE_TESTING\020c2\254\001\n\016WebhookService\022H" +
      "\n\005Error\022\024.api.v1.ErrorRequest\032\025.api.v1.E" +
      "rrorResponse\"\022\202\323\344\223\002\014\"\007/errors:\001*\022P\n\007Mess" +
      "age\022\026.api.v1.MessageRequest\032\027.api.v1.Mes" +
      "sageResponse\"\024\202\323\344\223\002\016\"\t/webhooks:\001*By\n\nco" +
      "m.api.v1B\025MerchantWebhooksProtoP\001Z\033api/p" +
      "roto/gen/api/v1;api_v1\242\002\003AXX\252\002\006Api.V1\312\002\006" +
      "Api\\V1\342\002\022Api\\V1\\GPBMetadata\352\002\007Api::V1b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.buf.validate.ValidateProto.getDescriptor(),
          com.error.v1.ErrorProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_api_v1_ErrorRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_api_v1_ErrorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_ErrorRequest_descriptor,
        new java.lang.String[] { });
    internal_static_api_v1_ErrorResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_api_v1_ErrorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_ErrorResponse_descriptor,
        new java.lang.String[] { "ErrorType", });
    internal_static_api_v1_MessageRequest_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_api_v1_MessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_MessageRequest_descriptor,
        new java.lang.String[] { });
    internal_static_api_v1_MessageResponse_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_api_v1_MessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_MessageResponse_descriptor,
        new java.lang.String[] { "MerchantWebhookMessage", "ChargeMessage", "ContractMessage", "UserAccountMessage", });
    internal_static_api_v1_MerchantWebhookMessage_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_api_v1_MerchantWebhookMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_MerchantWebhookMessage_descriptor,
        new java.lang.String[] { "Id", "Signature", "EventType", "Content", "CreatedAt", });
    internal_static_api_v1_ChargeMessage_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_api_v1_ChargeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_ChargeMessage_descriptor,
        new java.lang.String[] { "Id", "Customer", "Status", "Description", "MerchantName", "InitialAmount", "Discount", "FinalAmount", "AmountRefunded", "Currency", "ProcessedAt", "JammFee", "CreatedAt", "UpdatedAt", "Error", });
    internal_static_api_v1_ContractMessage_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_api_v1_ContractMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_ContractMessage_descriptor,
        new java.lang.String[] { "Customer", "CreatedAt", "ActivatedAt", "MerchantName", });
    internal_static_api_v1_UserAccountMessage_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_api_v1_UserAccountMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_UserAccountMessage_descriptor,
        new java.lang.String[] { "Customer", "Email", "DeletedAt", "MerchantName", });
    internal_static_api_v1_Error_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_api_v1_Error_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_Error_descriptor,
        new java.lang.String[] { "Code", "Message", "Details", });
    internal_static_api_v1_ErrorDetail_descriptor =
      getDescriptor().getMessageType(9);
    internal_static_api_v1_ErrorDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_ErrorDetail_descriptor,
        new java.lang.String[] { "Type", "Value", "Debug", });
    descriptor.resolveAllFeaturesImmutable();
    com.buf.validate.ValidateProto.getDescriptor();
    com.error.v1.ErrorProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.buf.validate.ValidateProto.field);
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
