// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/payment.proto
// Protobuf Java Version: 4.34.1

package com.api.v1;

@com.google.protobuf.Generated
public interface OnSessionPaymentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.v1.OnSessionPaymentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Optional customer ID for existing customers
   * If provided, the system will use the AddCharge flow and ignore buyer information
   * Must start with "cus-" prefix followed by additional characters
   * </pre>
   *
   * <code>optional string customer = 1 [json_name = "customer", (.buf.validate.field) = { ... }</code>
   * @return Whether the customer field is set.
   */
  boolean hasCustomer();
  /**
   * <pre>
   * Optional customer ID for existing customers
   * If provided, the system will use the AddCharge flow and ignore buyer information
   * Must start with "cus-" prefix followed by additional characters
   * </pre>
   *
   * <code>optional string customer = 1 [json_name = "customer", (.buf.validate.field) = { ... }</code>
   * @return The customer.
   */
  java.lang.String getCustomer();
  /**
   * <pre>
   * Optional customer ID for existing customers
   * If provided, the system will use the AddCharge flow and ignore buyer information
   * Must start with "cus-" prefix followed by additional characters
   * </pre>
   *
   * <code>optional string customer = 1 [json_name = "customer", (.buf.validate.field) = { ... }</code>
   * @return The bytes for customer.
   */
  com.google.protobuf.ByteString
      getCustomerBytes();

  /**
   * <pre>
   * Optional buyer information for new customers
   * If provided without a customer ID, the system will create a new customer and contract
   * </pre>
   *
   * <code>optional .api.v1.Buyer buyer = 2 [json_name = "buyer"];</code>
   * @return Whether the buyer field is set.
   */
  boolean hasBuyer();
  /**
   * <pre>
   * Optional buyer information for new customers
   * If provided without a customer ID, the system will create a new customer and contract
   * </pre>
   *
   * <code>optional .api.v1.Buyer buyer = 2 [json_name = "buyer"];</code>
   * @return The buyer.
   */
  com.api.v1.Buyer getBuyer();
  /**
   * <pre>
   * Optional buyer information for new customers
   * If provided without a customer ID, the system will create a new customer and contract
   * </pre>
   *
   * <code>optional .api.v1.Buyer buyer = 2 [json_name = "buyer"];</code>
   */
  com.api.v1.BuyerOrBuilder getBuyerOrBuilder();

  /**
   * <pre>
   * Optional charge information
   * If provided with customer ID: adds charge to existing customer
   * If provided with buyer info: creates contract with charge for new customer
   * If not provided with buyer info: creates contract without charge
   * </pre>
   *
   * <code>optional .api.v1.InitialCharge charge = 3 [json_name = "charge"];</code>
   * @return Whether the charge field is set.
   */
  boolean hasCharge();
  /**
   * <pre>
   * Optional charge information
   * If provided with customer ID: adds charge to existing customer
   * If provided with buyer info: creates contract with charge for new customer
   * If not provided with buyer info: creates contract without charge
   * </pre>
   *
   * <code>optional .api.v1.InitialCharge charge = 3 [json_name = "charge"];</code>
   * @return The charge.
   */
  com.api.v1.InitialCharge getCharge();
  /**
   * <pre>
   * Optional charge information
   * If provided with customer ID: adds charge to existing customer
   * If provided with buyer info: creates contract with charge for new customer
   * If not provided with buyer info: creates contract without charge
   * </pre>
   *
   * <code>optional .api.v1.InitialCharge charge = 3 [json_name = "charge"];</code>
   */
  com.api.v1.InitialChargeOrBuilder getChargeOrBuilder();

  /**
   * <pre>
   * Defaults to false if not provided.
   * If true, the charge is processed as a one-time payment and no contract is created.
   * If provided without a customer ID, the system will create a new customer.
   * Requires charge to be present.
   *
   * 未指定の場合はfalseがデフォルトです。
   * trueの場合、決済は一回限りの支払いとして処理され、契約は作成されません。
   * customer IDが提供されていない場合、新規顧客が作成されます。
   * chargeが必須です。
   * </pre>
   *
   * <code>bool one_time = 4 [json_name = "oneTime"];</code>
   * @return The oneTime.
   */
  boolean getOneTime();

  /**
   * <pre>
   * Optional redirect URLs for payment completion
   * If not provided, the user won't redirect to the merchant's page upon completing the payment
   * Used in payment flows to direct the customer after payment processing
   * </pre>
   *
   * <code>optional .api.v1.URL redirect = 10 [json_name = "redirect"];</code>
   * @return Whether the redirect field is set.
   */
  boolean hasRedirect();
  /**
   * <pre>
   * Optional redirect URLs for payment completion
   * If not provided, the user won't redirect to the merchant's page upon completing the payment
   * Used in payment flows to direct the customer after payment processing
   * </pre>
   *
   * <code>optional .api.v1.URL redirect = 10 [json_name = "redirect"];</code>
   * @return The redirect.
   */
  com.api.v1.URL getRedirect();
  /**
   * <pre>
   * Optional redirect URLs for payment completion
   * If not provided, the user won't redirect to the merchant's page upon completing the payment
   * Used in payment flows to direct the customer after payment processing
   * </pre>
   *
   * <code>optional .api.v1.URL redirect = 10 [json_name = "redirect"];</code>
   */
  com.api.v1.URLOrBuilder getRedirectOrBuilder();
}
