// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/payment.proto
// Protobuf Java Version: 4.34.0

package com.api.v1;

@com.google.protobuf.Generated
public interface OnSessionPaymentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.v1.OnSessionPaymentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Indicates whether the operation was successful
   * </pre>
   *
   * <code>bool success = 1 [json_name = "success"];</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <pre>
   * Error information when success is false
   * Only present when an error occurs
   * </pre>
   *
   * <code>optional .api.v1.OnSessionPaymentError error = 2 [json_name = "error"];</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <pre>
   * Error information when success is false
   * Only present when an error occurs
   * </pre>
   *
   * <code>optional .api.v1.OnSessionPaymentError error = 2 [json_name = "error"];</code>
   * @return The error.
   */
  com.api.v1.OnSessionPaymentError getError();
  /**
   * <pre>
   * Error information when success is false
   * Only present when an error occurs
   * </pre>
   *
   * <code>optional .api.v1.OnSessionPaymentError error = 2 [json_name = "error"];</code>
   */
  com.api.v1.OnSessionPaymentErrorOrBuilder getErrorOrBuilder();

  /**
   * <pre>
   * Success data when operation is successful
   * Only present when success is true
   * </pre>
   *
   * <code>optional .api.v1.OnSessionPaymentData data = 3 [json_name = "data"];</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <pre>
   * Success data when operation is successful
   * Only present when success is true
   * </pre>
   *
   * <code>optional .api.v1.OnSessionPaymentData data = 3 [json_name = "data"];</code>
   * @return The data.
   */
  com.api.v1.OnSessionPaymentData getData();
  /**
   * <pre>
   * Success data when operation is successful
   * Only present when success is true
   * </pre>
   *
   * <code>optional .api.v1.OnSessionPaymentData data = 3 [json_name = "data"];</code>
   */
  com.api.v1.OnSessionPaymentDataOrBuilder getDataOrBuilder();
}
