// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/common.proto
// Protobuf Java Version: 4.34.0

package com.api.v1;

@com.google.protobuf.Generated
public interface PaginationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.v1.Pagination)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 page_size = 1 [json_name = "pageSize", (.buf.validate.field) = { ... }</code>
   * @return The pageSize.
   */
  int getPageSize();

  /**
   * <code>string page_token = 2 [json_name = "pageToken"];</code>
   * @return The pageToken.
   */
  java.lang.String getPageToken();
  /**
   * <code>string page_token = 2 [json_name = "pageToken"];</code>
   * @return The bytes for pageToken.
   */
  com.google.protobuf.ByteString
      getPageTokenBytes();
}
