// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/payment.proto
// Protobuf Java Version: 4.33.5

package com.api.v1;

@com.google.protobuf.Generated
public interface RefundRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.v1.RefundRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The charge ID to refund.
   *
   * 返金する決済のID。
   *
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>string charge_id = 1 [json_name = "chargeId", (.buf.validate.field) = { ... }</code>
   * @return The chargeId.
   */
  java.lang.String getChargeId();
  /**
   * <pre>
   * The charge ID to refund.
   *
   * 返金する決済のID。
   *
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>string charge_id = 1 [json_name = "chargeId", (.buf.validate.field) = { ... }</code>
   * @return The bytes for chargeId.
   */
  com.google.protobuf.ByteString
      getChargeIdBytes();

  /**
   * <pre>
   * Optional refund amount in JPY.
   * If omitted, the full refundable amount is used.
   *
   * 返金金額（日本円）。
   * 省略した場合、全額返金となります。
   * </pre>
   *
   * <code>optional int32 amount = 2 [json_name = "amount", (.buf.validate.field) = { ... }</code>
   * @return Whether the amount field is set.
   */
  boolean hasAmount();
  /**
   * <pre>
   * Optional refund amount in JPY.
   * If omitted, the full refundable amount is used.
   *
   * 返金金額（日本円）。
   * 省略した場合、全額返金となります。
   * </pre>
   *
   * <code>optional int32 amount = 2 [json_name = "amount", (.buf.validate.field) = { ... }</code>
   * @return The amount.
   */
  int getAmount();
}
