// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/merchant_webhooks.proto
// Protobuf Java Version: 4.34.0

package com.api.v1;

/**
 * <pre>
 * RefundInfo contains refund-specific details for refund/cancel webhook events.
 * </pre>
 *
 * Protobuf type {@code api.v1.RefundInfo}
 */
@com.google.protobuf.Generated
public final class RefundInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:api.v1.RefundInfo)
    RefundInfoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "RefundInfo");
  }
  // Use RefundInfo.newBuilder() to construct.
  private RefundInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RefundInfo() {
    refundId_ = "";
    processedAt_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.api.v1.MerchantWebhooksProto.internal_static_api_v1_RefundInfo_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.api.v1.MerchantWebhooksProto.internal_static_api_v1_RefundInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.api.v1.MerchantWebhooksProto.internal_static_api_v1_RefundInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.api.v1.RefundInfo.class, com.api.v1.RefundInfo.Builder.class);
  }

  private int bitField0_;
  public static final int REFUND_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object refundId_ = "";
  /**
   * <pre>
   * External refund identifier (rfd-*).
   * </pre>
   *
   * <code>optional string refund_id = 1 [json_name = "refundId"];</code>
   * @return Whether the refundId field is set.
   */
  @java.lang.Override
  public boolean hasRefundId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * External refund identifier (rfd-*).
   * </pre>
   *
   * <code>optional string refund_id = 1 [json_name = "refundId"];</code>
   * @return The refundId.
   */
  @java.lang.Override
  public java.lang.String getRefundId() {
    java.lang.Object ref = refundId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      refundId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * External refund identifier (rfd-*).
   * </pre>
   *
   * <code>optional string refund_id = 1 [json_name = "refundId"];</code>
   * @return The bytes for refundId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRefundIdBytes() {
    java.lang.Object ref = refundId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      refundId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AMOUNT_REFUNDED_FIELD_NUMBER = 2;
  private int amountRefunded_ = 0;
  /**
   * <pre>
   * Amount refunded for this event.
   * </pre>
   *
   * <code>optional int32 amount_refunded = 2 [json_name = "amountRefunded"];</code>
   * @return Whether the amountRefunded field is set.
   */
  @java.lang.Override
  public boolean hasAmountRefunded() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Amount refunded for this event.
   * </pre>
   *
   * <code>optional int32 amount_refunded = 2 [json_name = "amountRefunded"];</code>
   * @return The amountRefunded.
   */
  @java.lang.Override
  public int getAmountRefunded() {
    return amountRefunded_;
  }

  public static final int JAMM_FEE_FIELD_NUMBER = 3;
  private int jammFee_ = 0;
  /**
   * <pre>
   * Jamm fee for this refund event.
   * </pre>
   *
   * <code>optional int32 jamm_fee = 3 [json_name = "jammFee"];</code>
   * @return Whether the jammFee field is set.
   */
  @java.lang.Override
  public boolean hasJammFee() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * Jamm fee for this refund event.
   * </pre>
   *
   * <code>optional int32 jamm_fee = 3 [json_name = "jammFee"];</code>
   * @return The jammFee.
   */
  @java.lang.Override
  public int getJammFee() {
    return jammFee_;
  }

  public static final int CONSUMPTION_TAX_FIELD_NUMBER = 4;
  private int consumptionTax_ = 0;
  /**
   * <pre>
   * Consumption tax (10% of the Jamm fee).
   * </pre>
   *
   * <code>optional int32 consumption_tax = 4 [json_name = "consumptionTax"];</code>
   * @return Whether the consumptionTax field is set.
   */
  @java.lang.Override
  public boolean hasConsumptionTax() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * Consumption tax (10% of the Jamm fee).
   * </pre>
   *
   * <code>optional int32 consumption_tax = 4 [json_name = "consumptionTax"];</code>
   * @return The consumptionTax.
   */
  @java.lang.Override
  public int getConsumptionTax() {
    return consumptionTax_;
  }

  public static final int ORIGINAL_TRANSACTION_FEE_WAIVED_FIELD_NUMBER = 5;
  private boolean originalTransactionFeeWaived_ = false;
  /**
   * <pre>
   * Whether the original transaction's Jamm fee was waived (true for same-day cancel).
   * </pre>
   *
   * <code>optional bool original_transaction_fee_waived = 5 [json_name = "originalTransactionFeeWaived"];</code>
   * @return Whether the originalTransactionFeeWaived field is set.
   */
  @java.lang.Override
  public boolean hasOriginalTransactionFeeWaived() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <pre>
   * Whether the original transaction's Jamm fee was waived (true for same-day cancel).
   * </pre>
   *
   * <code>optional bool original_transaction_fee_waived = 5 [json_name = "originalTransactionFeeWaived"];</code>
   * @return The originalTransactionFeeWaived.
   */
  @java.lang.Override
  public boolean getOriginalTransactionFeeWaived() {
    return originalTransactionFeeWaived_;
  }

  public static final int ERROR_FIELD_NUMBER = 6;
  private com.api.v1.Error error_;
  /**
   * <pre>
   * Error details, present only on refund_failed events.
   * </pre>
   *
   * <code>optional .api.v1.Error error = 6 [json_name = "error"];</code>
   * @return Whether the error field is set.
   */
  @java.lang.Override
  public boolean hasError() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <pre>
   * Error details, present only on refund_failed events.
   * </pre>
   *
   * <code>optional .api.v1.Error error = 6 [json_name = "error"];</code>
   * @return The error.
   */
  @java.lang.Override
  public com.api.v1.Error getError() {
    return error_ == null ? com.api.v1.Error.getDefaultInstance() : error_;
  }
  /**
   * <pre>
   * Error details, present only on refund_failed events.
   * </pre>
   *
   * <code>optional .api.v1.Error error = 6 [json_name = "error"];</code>
   */
  @java.lang.Override
  public com.api.v1.ErrorOrBuilder getErrorOrBuilder() {
    return error_ == null ? com.api.v1.Error.getDefaultInstance() : error_;
  }

  public static final int PROCESSED_AT_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object processedAt_ = "";
  /**
   * <pre>
   * When the refund was processed (not present on refund_failed events).
   * </pre>
   *
   * <code>optional string processed_at = 7 [json_name = "processedAt"];</code>
   * @return Whether the processedAt field is set.
   */
  @java.lang.Override
  public boolean hasProcessedAt() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <pre>
   * When the refund was processed (not present on refund_failed events).
   * </pre>
   *
   * <code>optional string processed_at = 7 [json_name = "processedAt"];</code>
   * @return The processedAt.
   */
  @java.lang.Override
  public java.lang.String getProcessedAt() {
    java.lang.Object ref = processedAt_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      processedAt_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * When the refund was processed (not present on refund_failed events).
   * </pre>
   *
   * <code>optional string processed_at = 7 [json_name = "processedAt"];</code>
   * @return The bytes for processedAt.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProcessedAtBytes() {
    java.lang.Object ref = processedAt_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      processedAt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, refundId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(2, amountRefunded_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(3, jammFee_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeInt32(4, consumptionTax_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeBool(5, originalTransactionFeeWaived_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeMessage(6, getError());
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, processedAt_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, refundId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, amountRefunded_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, jammFee_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, consumptionTax_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, originalTransactionFeeWaived_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getError());
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, processedAt_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.api.v1.RefundInfo)) {
      return super.equals(obj);
    }
    com.api.v1.RefundInfo other = (com.api.v1.RefundInfo) obj;

    if (hasRefundId() != other.hasRefundId()) return false;
    if (hasRefundId()) {
      if (!getRefundId()
          .equals(other.getRefundId())) return false;
    }
    if (hasAmountRefunded() != other.hasAmountRefunded()) return false;
    if (hasAmountRefunded()) {
      if (getAmountRefunded()
          != other.getAmountRefunded()) return false;
    }
    if (hasJammFee() != other.hasJammFee()) return false;
    if (hasJammFee()) {
      if (getJammFee()
          != other.getJammFee()) return false;
    }
    if (hasConsumptionTax() != other.hasConsumptionTax()) return false;
    if (hasConsumptionTax()) {
      if (getConsumptionTax()
          != other.getConsumptionTax()) return false;
    }
    if (hasOriginalTransactionFeeWaived() != other.hasOriginalTransactionFeeWaived()) return false;
    if (hasOriginalTransactionFeeWaived()) {
      if (getOriginalTransactionFeeWaived()
          != other.getOriginalTransactionFeeWaived()) return false;
    }
    if (hasError() != other.hasError()) return false;
    if (hasError()) {
      if (!getError()
          .equals(other.getError())) return false;
    }
    if (hasProcessedAt() != other.hasProcessedAt()) return false;
    if (hasProcessedAt()) {
      if (!getProcessedAt()
          .equals(other.getProcessedAt())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRefundId()) {
      hash = (37 * hash) + REFUND_ID_FIELD_NUMBER;
      hash = (53 * hash) + getRefundId().hashCode();
    }
    if (hasAmountRefunded()) {
      hash = (37 * hash) + AMOUNT_REFUNDED_FIELD_NUMBER;
      hash = (53 * hash) + getAmountRefunded();
    }
    if (hasJammFee()) {
      hash = (37 * hash) + JAMM_FEE_FIELD_NUMBER;
      hash = (53 * hash) + getJammFee();
    }
    if (hasConsumptionTax()) {
      hash = (37 * hash) + CONSUMPTION_TAX_FIELD_NUMBER;
      hash = (53 * hash) + getConsumptionTax();
    }
    if (hasOriginalTransactionFeeWaived()) {
      hash = (37 * hash) + ORIGINAL_TRANSACTION_FEE_WAIVED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getOriginalTransactionFeeWaived());
    }
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    if (hasProcessedAt()) {
      hash = (37 * hash) + PROCESSED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getProcessedAt().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.api.v1.RefundInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.api.v1.RefundInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.api.v1.RefundInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.api.v1.RefundInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.api.v1.RefundInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.api.v1.RefundInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.api.v1.RefundInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.api.v1.RefundInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.api.v1.RefundInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.api.v1.RefundInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.api.v1.RefundInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.api.v1.RefundInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.api.v1.RefundInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * RefundInfo contains refund-specific details for refund/cancel webhook events.
   * </pre>
   *
   * Protobuf type {@code api.v1.RefundInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.v1.RefundInfo)
      com.api.v1.RefundInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.api.v1.MerchantWebhooksProto.internal_static_api_v1_RefundInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.api.v1.MerchantWebhooksProto.internal_static_api_v1_RefundInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.api.v1.RefundInfo.class, com.api.v1.RefundInfo.Builder.class);
    }

    // Construct using com.api.v1.RefundInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetErrorFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      refundId_ = "";
      amountRefunded_ = 0;
      jammFee_ = 0;
      consumptionTax_ = 0;
      originalTransactionFeeWaived_ = false;
      error_ = null;
      if (errorBuilder_ != null) {
        errorBuilder_.dispose();
        errorBuilder_ = null;
      }
      processedAt_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.api.v1.MerchantWebhooksProto.internal_static_api_v1_RefundInfo_descriptor;
    }

    @java.lang.Override
    public com.api.v1.RefundInfo getDefaultInstanceForType() {
      return com.api.v1.RefundInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.api.v1.RefundInfo build() {
      com.api.v1.RefundInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.api.v1.RefundInfo buildPartial() {
      com.api.v1.RefundInfo result = new com.api.v1.RefundInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.api.v1.RefundInfo result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.refundId_ = refundId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.amountRefunded_ = amountRefunded_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.jammFee_ = jammFee_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.consumptionTax_ = consumptionTax_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.originalTransactionFeeWaived_ = originalTransactionFeeWaived_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.error_ = errorBuilder_ == null
            ? error_
            : errorBuilder_.build();
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.processedAt_ = processedAt_;
        to_bitField0_ |= 0x00000040;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.api.v1.RefundInfo) {
        return mergeFrom((com.api.v1.RefundInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.api.v1.RefundInfo other) {
      if (other == com.api.v1.RefundInfo.getDefaultInstance()) return this;
      if (other.hasRefundId()) {
        refundId_ = other.refundId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasAmountRefunded()) {
        setAmountRefunded(other.getAmountRefunded());
      }
      if (other.hasJammFee()) {
        setJammFee(other.getJammFee());
      }
      if (other.hasConsumptionTax()) {
        setConsumptionTax(other.getConsumptionTax());
      }
      if (other.hasOriginalTransactionFeeWaived()) {
        setOriginalTransactionFeeWaived(other.getOriginalTransactionFeeWaived());
      }
      if (other.hasError()) {
        mergeError(other.getError());
      }
      if (other.hasProcessedAt()) {
        processedAt_ = other.processedAt_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              refundId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              amountRefunded_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              jammFee_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              consumptionTax_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              originalTransactionFeeWaived_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              input.readMessage(
                  internalGetErrorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              processedAt_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object refundId_ = "";
    /**
     * <pre>
     * External refund identifier (rfd-*).
     * </pre>
     *
     * <code>optional string refund_id = 1 [json_name = "refundId"];</code>
     * @return Whether the refundId field is set.
     */
    public boolean hasRefundId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * External refund identifier (rfd-*).
     * </pre>
     *
     * <code>optional string refund_id = 1 [json_name = "refundId"];</code>
     * @return The refundId.
     */
    public java.lang.String getRefundId() {
      java.lang.Object ref = refundId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        refundId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * External refund identifier (rfd-*).
     * </pre>
     *
     * <code>optional string refund_id = 1 [json_name = "refundId"];</code>
     * @return The bytes for refundId.
     */
    public com.google.protobuf.ByteString
        getRefundIdBytes() {
      java.lang.Object ref = refundId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        refundId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * External refund identifier (rfd-*).
     * </pre>
     *
     * <code>optional string refund_id = 1 [json_name = "refundId"];</code>
     * @param value The refundId to set.
     * @return This builder for chaining.
     */
    public Builder setRefundId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      refundId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * External refund identifier (rfd-*).
     * </pre>
     *
     * <code>optional string refund_id = 1 [json_name = "refundId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRefundId() {
      refundId_ = getDefaultInstance().getRefundId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * External refund identifier (rfd-*).
     * </pre>
     *
     * <code>optional string refund_id = 1 [json_name = "refundId"];</code>
     * @param value The bytes for refundId to set.
     * @return This builder for chaining.
     */
    public Builder setRefundIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      refundId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int amountRefunded_ ;
    /**
     * <pre>
     * Amount refunded for this event.
     * </pre>
     *
     * <code>optional int32 amount_refunded = 2 [json_name = "amountRefunded"];</code>
     * @return Whether the amountRefunded field is set.
     */
    @java.lang.Override
    public boolean hasAmountRefunded() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Amount refunded for this event.
     * </pre>
     *
     * <code>optional int32 amount_refunded = 2 [json_name = "amountRefunded"];</code>
     * @return The amountRefunded.
     */
    @java.lang.Override
    public int getAmountRefunded() {
      return amountRefunded_;
    }
    /**
     * <pre>
     * Amount refunded for this event.
     * </pre>
     *
     * <code>optional int32 amount_refunded = 2 [json_name = "amountRefunded"];</code>
     * @param value The amountRefunded to set.
     * @return This builder for chaining.
     */
    public Builder setAmountRefunded(int value) {

      amountRefunded_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Amount refunded for this event.
     * </pre>
     *
     * <code>optional int32 amount_refunded = 2 [json_name = "amountRefunded"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAmountRefunded() {
      bitField0_ = (bitField0_ & ~0x00000002);
      amountRefunded_ = 0;
      onChanged();
      return this;
    }

    private int jammFee_ ;
    /**
     * <pre>
     * Jamm fee for this refund event.
     * </pre>
     *
     * <code>optional int32 jamm_fee = 3 [json_name = "jammFee"];</code>
     * @return Whether the jammFee field is set.
     */
    @java.lang.Override
    public boolean hasJammFee() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Jamm fee for this refund event.
     * </pre>
     *
     * <code>optional int32 jamm_fee = 3 [json_name = "jammFee"];</code>
     * @return The jammFee.
     */
    @java.lang.Override
    public int getJammFee() {
      return jammFee_;
    }
    /**
     * <pre>
     * Jamm fee for this refund event.
     * </pre>
     *
     * <code>optional int32 jamm_fee = 3 [json_name = "jammFee"];</code>
     * @param value The jammFee to set.
     * @return This builder for chaining.
     */
    public Builder setJammFee(int value) {

      jammFee_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Jamm fee for this refund event.
     * </pre>
     *
     * <code>optional int32 jamm_fee = 3 [json_name = "jammFee"];</code>
     * @return This builder for chaining.
     */
    public Builder clearJammFee() {
      bitField0_ = (bitField0_ & ~0x00000004);
      jammFee_ = 0;
      onChanged();
      return this;
    }

    private int consumptionTax_ ;
    /**
     * <pre>
     * Consumption tax (10% of the Jamm fee).
     * </pre>
     *
     * <code>optional int32 consumption_tax = 4 [json_name = "consumptionTax"];</code>
     * @return Whether the consumptionTax field is set.
     */
    @java.lang.Override
    public boolean hasConsumptionTax() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Consumption tax (10% of the Jamm fee).
     * </pre>
     *
     * <code>optional int32 consumption_tax = 4 [json_name = "consumptionTax"];</code>
     * @return The consumptionTax.
     */
    @java.lang.Override
    public int getConsumptionTax() {
      return consumptionTax_;
    }
    /**
     * <pre>
     * Consumption tax (10% of the Jamm fee).
     * </pre>
     *
     * <code>optional int32 consumption_tax = 4 [json_name = "consumptionTax"];</code>
     * @param value The consumptionTax to set.
     * @return This builder for chaining.
     */
    public Builder setConsumptionTax(int value) {

      consumptionTax_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Consumption tax (10% of the Jamm fee).
     * </pre>
     *
     * <code>optional int32 consumption_tax = 4 [json_name = "consumptionTax"];</code>
     * @return This builder for chaining.
     */
    public Builder clearConsumptionTax() {
      bitField0_ = (bitField0_ & ~0x00000008);
      consumptionTax_ = 0;
      onChanged();
      return this;
    }

    private boolean originalTransactionFeeWaived_ ;
    /**
     * <pre>
     * Whether the original transaction's Jamm fee was waived (true for same-day cancel).
     * </pre>
     *
     * <code>optional bool original_transaction_fee_waived = 5 [json_name = "originalTransactionFeeWaived"];</code>
     * @return Whether the originalTransactionFeeWaived field is set.
     */
    @java.lang.Override
    public boolean hasOriginalTransactionFeeWaived() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * Whether the original transaction's Jamm fee was waived (true for same-day cancel).
     * </pre>
     *
     * <code>optional bool original_transaction_fee_waived = 5 [json_name = "originalTransactionFeeWaived"];</code>
     * @return The originalTransactionFeeWaived.
     */
    @java.lang.Override
    public boolean getOriginalTransactionFeeWaived() {
      return originalTransactionFeeWaived_;
    }
    /**
     * <pre>
     * Whether the original transaction's Jamm fee was waived (true for same-day cancel).
     * </pre>
     *
     * <code>optional bool original_transaction_fee_waived = 5 [json_name = "originalTransactionFeeWaived"];</code>
     * @param value The originalTransactionFeeWaived to set.
     * @return This builder for chaining.
     */
    public Builder setOriginalTransactionFeeWaived(boolean value) {

      originalTransactionFeeWaived_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether the original transaction's Jamm fee was waived (true for same-day cancel).
     * </pre>
     *
     * <code>optional bool original_transaction_fee_waived = 5 [json_name = "originalTransactionFeeWaived"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOriginalTransactionFeeWaived() {
      bitField0_ = (bitField0_ & ~0x00000010);
      originalTransactionFeeWaived_ = false;
      onChanged();
      return this;
    }

    private com.api.v1.Error error_;
    private com.google.protobuf.SingleFieldBuilder<
        com.api.v1.Error, com.api.v1.Error.Builder, com.api.v1.ErrorOrBuilder> errorBuilder_;
    /**
     * <pre>
     * Error details, present only on refund_failed events.
     * </pre>
     *
     * <code>optional .api.v1.Error error = 6 [json_name = "error"];</code>
     * @return Whether the error field is set.
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * Error details, present only on refund_failed events.
     * </pre>
     *
     * <code>optional .api.v1.Error error = 6 [json_name = "error"];</code>
     * @return The error.
     */
    public com.api.v1.Error getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? com.api.v1.Error.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Error details, present only on refund_failed events.
     * </pre>
     *
     * <code>optional .api.v1.Error error = 6 [json_name = "error"];</code>
     */
    public Builder setError(com.api.v1.Error value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
      } else {
        errorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Error details, present only on refund_failed events.
     * </pre>
     *
     * <code>optional .api.v1.Error error = 6 [json_name = "error"];</code>
     */
    public Builder setError(
        com.api.v1.Error.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Error details, present only on refund_failed events.
     * </pre>
     *
     * <code>optional .api.v1.Error error = 6 [json_name = "error"];</code>
     */
    public Builder mergeError(com.api.v1.Error value) {
      if (errorBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          error_ != null &&
          error_ != com.api.v1.Error.getDefaultInstance()) {
          getErrorBuilder().mergeFrom(value);
        } else {
          error_ = value;
        }
      } else {
        errorBuilder_.mergeFrom(value);
      }
      if (error_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Error details, present only on refund_failed events.
     * </pre>
     *
     * <code>optional .api.v1.Error error = 6 [json_name = "error"];</code>
     */
    public Builder clearError() {
      bitField0_ = (bitField0_ & ~0x00000020);
      error_ = null;
      if (errorBuilder_ != null) {
        errorBuilder_.dispose();
        errorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Error details, present only on refund_failed events.
     * </pre>
     *
     * <code>optional .api.v1.Error error = 6 [json_name = "error"];</code>
     */
    public com.api.v1.Error.Builder getErrorBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return internalGetErrorFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Error details, present only on refund_failed events.
     * </pre>
     *
     * <code>optional .api.v1.Error error = 6 [json_name = "error"];</code>
     */
    public com.api.v1.ErrorOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            com.api.v1.Error.getDefaultInstance() : error_;
      }
    }
    /**
     * <pre>
     * Error details, present only on refund_failed events.
     * </pre>
     *
     * <code>optional .api.v1.Error error = 6 [json_name = "error"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.api.v1.Error, com.api.v1.Error.Builder, com.api.v1.ErrorOrBuilder> 
        internalGetErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.api.v1.Error, com.api.v1.Error.Builder, com.api.v1.ErrorOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }

    private java.lang.Object processedAt_ = "";
    /**
     * <pre>
     * When the refund was processed (not present on refund_failed events).
     * </pre>
     *
     * <code>optional string processed_at = 7 [json_name = "processedAt"];</code>
     * @return Whether the processedAt field is set.
     */
    public boolean hasProcessedAt() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * When the refund was processed (not present on refund_failed events).
     * </pre>
     *
     * <code>optional string processed_at = 7 [json_name = "processedAt"];</code>
     * @return The processedAt.
     */
    public java.lang.String getProcessedAt() {
      java.lang.Object ref = processedAt_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        processedAt_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * When the refund was processed (not present on refund_failed events).
     * </pre>
     *
     * <code>optional string processed_at = 7 [json_name = "processedAt"];</code>
     * @return The bytes for processedAt.
     */
    public com.google.protobuf.ByteString
        getProcessedAtBytes() {
      java.lang.Object ref = processedAt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        processedAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * When the refund was processed (not present on refund_failed events).
     * </pre>
     *
     * <code>optional string processed_at = 7 [json_name = "processedAt"];</code>
     * @param value The processedAt to set.
     * @return This builder for chaining.
     */
    public Builder setProcessedAt(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      processedAt_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * When the refund was processed (not present on refund_failed events).
     * </pre>
     *
     * <code>optional string processed_at = 7 [json_name = "processedAt"];</code>
     * @return This builder for chaining.
     */
    public Builder clearProcessedAt() {
      processedAt_ = getDefaultInstance().getProcessedAt();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * When the refund was processed (not present on refund_failed events).
     * </pre>
     *
     * <code>optional string processed_at = 7 [json_name = "processedAt"];</code>
     * @param value The bytes for processedAt to set.
     * @return This builder for chaining.
     */
    public Builder setProcessedAtBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      processedAt_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:api.v1.RefundInfo)
  }

  // @@protoc_insertion_point(class_scope:api.v1.RefundInfo)
  private static final com.api.v1.RefundInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.api.v1.RefundInfo();
  }

  public static com.api.v1.RefundInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RefundInfo>
      PARSER = new com.google.protobuf.AbstractParser<RefundInfo>() {
    @java.lang.Override
    public RefundInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RefundInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RefundInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.api.v1.RefundInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

