// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/merchant_webhooks.proto
// Protobuf Java Version: 4.34.1

package com.api.v1;

@com.google.protobuf.Generated
public interface RefundInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.v1.RefundInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * External refund identifier (rfd-*).
   * </pre>
   *
   * <code>optional string refund_id = 1 [json_name = "refundId"];</code>
   * @return Whether the refundId field is set.
   */
  boolean hasRefundId();
  /**
   * <pre>
   * External refund identifier (rfd-*).
   * </pre>
   *
   * <code>optional string refund_id = 1 [json_name = "refundId"];</code>
   * @return The refundId.
   */
  java.lang.String getRefundId();
  /**
   * <pre>
   * External refund identifier (rfd-*).
   * </pre>
   *
   * <code>optional string refund_id = 1 [json_name = "refundId"];</code>
   * @return The bytes for refundId.
   */
  com.google.protobuf.ByteString
      getRefundIdBytes();

  /**
   * <pre>
   * Amount refunded for this event.
   * </pre>
   *
   * <code>optional int32 amount_refunded = 2 [json_name = "amountRefunded"];</code>
   * @return Whether the amountRefunded field is set.
   */
  boolean hasAmountRefunded();
  /**
   * <pre>
   * Amount refunded for this event.
   * </pre>
   *
   * <code>optional int32 amount_refunded = 2 [json_name = "amountRefunded"];</code>
   * @return The amountRefunded.
   */
  int getAmountRefunded();

  /**
   * <pre>
   * Jamm fee for this refund event.
   * </pre>
   *
   * <code>optional int32 jamm_fee = 3 [json_name = "jammFee"];</code>
   * @return Whether the jammFee field is set.
   */
  boolean hasJammFee();
  /**
   * <pre>
   * Jamm fee for this refund event.
   * </pre>
   *
   * <code>optional int32 jamm_fee = 3 [json_name = "jammFee"];</code>
   * @return The jammFee.
   */
  int getJammFee();

  /**
   * <pre>
   * Consumption tax (10% of the Jamm fee).
   * </pre>
   *
   * <code>optional int32 consumption_tax = 4 [json_name = "consumptionTax"];</code>
   * @return Whether the consumptionTax field is set.
   */
  boolean hasConsumptionTax();
  /**
   * <pre>
   * Consumption tax (10% of the Jamm fee).
   * </pre>
   *
   * <code>optional int32 consumption_tax = 4 [json_name = "consumptionTax"];</code>
   * @return The consumptionTax.
   */
  int getConsumptionTax();

  /**
   * <pre>
   * Whether the original transaction's Jamm fee was waived (true for same-day cancel).
   * </pre>
   *
   * <code>optional bool original_transaction_fee_waived = 5 [json_name = "originalTransactionFeeWaived"];</code>
   * @return Whether the originalTransactionFeeWaived field is set.
   */
  boolean hasOriginalTransactionFeeWaived();
  /**
   * <pre>
   * Whether the original transaction's Jamm fee was waived (true for same-day cancel).
   * </pre>
   *
   * <code>optional bool original_transaction_fee_waived = 5 [json_name = "originalTransactionFeeWaived"];</code>
   * @return The originalTransactionFeeWaived.
   */
  boolean getOriginalTransactionFeeWaived();

  /**
   * <pre>
   * Error details, present only on refund_failed events.
   * </pre>
   *
   * <code>optional .api.v1.Error error = 6 [json_name = "error"];</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <pre>
   * Error details, present only on refund_failed events.
   * </pre>
   *
   * <code>optional .api.v1.Error error = 6 [json_name = "error"];</code>
   * @return The error.
   */
  com.api.v1.Error getError();
  /**
   * <pre>
   * Error details, present only on refund_failed events.
   * </pre>
   *
   * <code>optional .api.v1.Error error = 6 [json_name = "error"];</code>
   */
  com.api.v1.ErrorOrBuilder getErrorOrBuilder();

  /**
   * <pre>
   * When the refund was processed (not present on refund_failed events).
   * </pre>
   *
   * <code>optional string processed_at = 7 [json_name = "processedAt"];</code>
   * @return Whether the processedAt field is set.
   */
  boolean hasProcessedAt();
  /**
   * <pre>
   * When the refund was processed (not present on refund_failed events).
   * </pre>
   *
   * <code>optional string processed_at = 7 [json_name = "processedAt"];</code>
   * @return The processedAt.
   */
  java.lang.String getProcessedAt();
  /**
   * <pre>
   * When the refund was processed (not present on refund_failed events).
   * </pre>
   *
   * <code>optional string processed_at = 7 [json_name = "processedAt"];</code>
   * @return The bytes for processedAt.
   */
  com.google.protobuf.ByteString
      getProcessedAtBytes();
}
