// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/bank.proto
// Protobuf Java Version: 4.34.1

package com.api.v1;

/**
 * Protobuf type {@code api.v1.SearchBranchesResponse}
 */
@com.google.protobuf.Generated
public final class SearchBranchesResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:api.v1.SearchBranchesResponse)
    SearchBranchesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "SearchBranchesResponse");
  }
  // Use SearchBranchesResponse.newBuilder() to construct.
  private SearchBranchesResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SearchBranchesResponse() {
    branches_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.api.v1.BankProto.internal_static_api_v1_SearchBranchesResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.api.v1.BankProto.internal_static_api_v1_SearchBranchesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.api.v1.BankProto.internal_static_api_v1_SearchBranchesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.api.v1.SearchBranchesResponse.class, com.api.v1.SearchBranchesResponse.Builder.class);
  }

  public static final int BRANCHES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.api.v1.BankBranch> branches_;
  /**
   * <code>repeated .api.v1.BankBranch branches = 1 [json_name = "branches"];</code>
   */
  @java.lang.Override
  public java.util.List<com.api.v1.BankBranch> getBranchesList() {
    return branches_;
  }
  /**
   * <code>repeated .api.v1.BankBranch branches = 1 [json_name = "branches"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.api.v1.BankBranchOrBuilder> 
      getBranchesOrBuilderList() {
    return branches_;
  }
  /**
   * <code>repeated .api.v1.BankBranch branches = 1 [json_name = "branches"];</code>
   */
  @java.lang.Override
  public int getBranchesCount() {
    return branches_.size();
  }
  /**
   * <code>repeated .api.v1.BankBranch branches = 1 [json_name = "branches"];</code>
   */
  @java.lang.Override
  public com.api.v1.BankBranch getBranches(int index) {
    return branches_.get(index);
  }
  /**
   * <code>repeated .api.v1.BankBranch branches = 1 [json_name = "branches"];</code>
   */
  @java.lang.Override
  public com.api.v1.BankBranchOrBuilder getBranchesOrBuilder(
      int index) {
    return branches_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < branches_.size(); i++) {
      output.writeMessage(1, branches_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;

        {
          final int count = branches_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(branches_.get(i));
          }
          size += 1 * count;
        }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.api.v1.SearchBranchesResponse)) {
      return super.equals(obj);
    }
    com.api.v1.SearchBranchesResponse other = (com.api.v1.SearchBranchesResponse) obj;

    if (!getBranchesList()
        .equals(other.getBranchesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getBranchesCount() > 0) {
      hash = (37 * hash) + BRANCHES_FIELD_NUMBER;
      hash = (53 * hash) + getBranchesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.api.v1.SearchBranchesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.api.v1.SearchBranchesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.api.v1.SearchBranchesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.api.v1.SearchBranchesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.api.v1.SearchBranchesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.api.v1.SearchBranchesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.api.v1.SearchBranchesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.api.v1.SearchBranchesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.api.v1.SearchBranchesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.api.v1.SearchBranchesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.api.v1.SearchBranchesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.api.v1.SearchBranchesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.api.v1.SearchBranchesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code api.v1.SearchBranchesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.v1.SearchBranchesResponse)
      com.api.v1.SearchBranchesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.api.v1.BankProto.internal_static_api_v1_SearchBranchesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.api.v1.BankProto.internal_static_api_v1_SearchBranchesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.api.v1.SearchBranchesResponse.class, com.api.v1.SearchBranchesResponse.Builder.class);
    }

    // Construct using com.api.v1.SearchBranchesResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (branchesBuilder_ == null) {
        branches_ = java.util.Collections.emptyList();
      } else {
        branches_ = null;
        branchesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.api.v1.BankProto.internal_static_api_v1_SearchBranchesResponse_descriptor;
    }

    @java.lang.Override
    public com.api.v1.SearchBranchesResponse getDefaultInstanceForType() {
      return com.api.v1.SearchBranchesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.api.v1.SearchBranchesResponse build() {
      com.api.v1.SearchBranchesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.api.v1.SearchBranchesResponse buildPartial() {
      com.api.v1.SearchBranchesResponse result = new com.api.v1.SearchBranchesResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.api.v1.SearchBranchesResponse result) {
      if (branchesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          branches_ = java.util.Collections.unmodifiableList(branches_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.branches_ = branches_;
      } else {
        result.branches_ = branchesBuilder_.build();
      }
    }

    private void buildPartial0(com.api.v1.SearchBranchesResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.api.v1.SearchBranchesResponse) {
        return mergeFrom((com.api.v1.SearchBranchesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.api.v1.SearchBranchesResponse other) {
      if (other == com.api.v1.SearchBranchesResponse.getDefaultInstance()) return this;
      if (branchesBuilder_ == null) {
        if (!other.branches_.isEmpty()) {
          if (branches_.isEmpty()) {
            branches_ = other.branches_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBranchesIsMutable();
            branches_.addAll(other.branches_);
          }
          onChanged();
        }
      } else {
        if (!other.branches_.isEmpty()) {
          if (branchesBuilder_.isEmpty()) {
            branchesBuilder_.dispose();
            branchesBuilder_ = null;
            branches_ = other.branches_;
            bitField0_ = (bitField0_ & ~0x00000001);
            branchesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetBranchesFieldBuilder() : null;
          } else {
            branchesBuilder_.addAllMessages(other.branches_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.api.v1.BankBranch m =
                  input.readMessage(
                      com.api.v1.BankBranch.parser(),
                      extensionRegistry);
              if (branchesBuilder_ == null) {
                ensureBranchesIsMutable();
                branches_.add(m);
              } else {
                branchesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.api.v1.BankBranch> branches_ =
      java.util.Collections.emptyList();
    private void ensureBranchesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        branches_ = new java.util.ArrayList<com.api.v1.BankBranch>(branches_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.api.v1.BankBranch, com.api.v1.BankBranch.Builder, com.api.v1.BankBranchOrBuilder> branchesBuilder_;

    /**
     * <code>repeated .api.v1.BankBranch branches = 1 [json_name = "branches"];</code>
     */
    public java.util.List<com.api.v1.BankBranch> getBranchesList() {
      if (branchesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(branches_);
      } else {
        return branchesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .api.v1.BankBranch branches = 1 [json_name = "branches"];</code>
     */
    public int getBranchesCount() {
      if (branchesBuilder_ == null) {
        return branches_.size();
      } else {
        return branchesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .api.v1.BankBranch branches = 1 [json_name = "branches"];</code>
     */
    public com.api.v1.BankBranch getBranches(int index) {
      if (branchesBuilder_ == null) {
        return branches_.get(index);
      } else {
        return branchesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .api.v1.BankBranch branches = 1 [json_name = "branches"];</code>
     */
    public Builder setBranches(
        int index, com.api.v1.BankBranch value) {
      if (branchesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBranchesIsMutable();
        branches_.set(index, value);
        onChanged();
      } else {
        branchesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .api.v1.BankBranch branches = 1 [json_name = "branches"];</code>
     */
    public Builder setBranches(
        int index, com.api.v1.BankBranch.Builder builderForValue) {
      if (branchesBuilder_ == null) {
        ensureBranchesIsMutable();
        branches_.set(index, builderForValue.build());
        onChanged();
      } else {
        branchesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .api.v1.BankBranch branches = 1 [json_name = "branches"];</code>
     */
    public Builder addBranches(com.api.v1.BankBranch value) {
      if (branchesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBranchesIsMutable();
        branches_.add(value);
        onChanged();
      } else {
        branchesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .api.v1.BankBranch branches = 1 [json_name = "branches"];</code>
     */
    public Builder addBranches(
        int index, com.api.v1.BankBranch value) {
      if (branchesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBranchesIsMutable();
        branches_.add(index, value);
        onChanged();
      } else {
        branchesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .api.v1.BankBranch branches = 1 [json_name = "branches"];</code>
     */
    public Builder addBranches(
        com.api.v1.BankBranch.Builder builderForValue) {
      if (branchesBuilder_ == null) {
        ensureBranchesIsMutable();
        branches_.add(builderForValue.build());
        onChanged();
      } else {
        branchesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .api.v1.BankBranch branches = 1 [json_name = "branches"];</code>
     */
    public Builder addBranches(
        int index, com.api.v1.BankBranch.Builder builderForValue) {
      if (branchesBuilder_ == null) {
        ensureBranchesIsMutable();
        branches_.add(index, builderForValue.build());
        onChanged();
      } else {
        branchesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .api.v1.BankBranch branches = 1 [json_name = "branches"];</code>
     */
    public Builder addAllBranches(
        java.lang.Iterable<? extends com.api.v1.BankBranch> values) {
      if (branchesBuilder_ == null) {
        ensureBranchesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, branches_);
        onChanged();
      } else {
        branchesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .api.v1.BankBranch branches = 1 [json_name = "branches"];</code>
     */
    public Builder clearBranches() {
      if (branchesBuilder_ == null) {
        branches_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        branchesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .api.v1.BankBranch branches = 1 [json_name = "branches"];</code>
     */
    public Builder removeBranches(int index) {
      if (branchesBuilder_ == null) {
        ensureBranchesIsMutable();
        branches_.remove(index);
        onChanged();
      } else {
        branchesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .api.v1.BankBranch branches = 1 [json_name = "branches"];</code>
     */
    public com.api.v1.BankBranch.Builder getBranchesBuilder(
        int index) {
      return internalGetBranchesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .api.v1.BankBranch branches = 1 [json_name = "branches"];</code>
     */
    public com.api.v1.BankBranchOrBuilder getBranchesOrBuilder(
        int index) {
      if (branchesBuilder_ == null) {
        return branches_.get(index);  } else {
        return branchesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .api.v1.BankBranch branches = 1 [json_name = "branches"];</code>
     */
    public java.util.List<? extends com.api.v1.BankBranchOrBuilder> 
         getBranchesOrBuilderList() {
      if (branchesBuilder_ != null) {
        return branchesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(branches_);
      }
    }
    /**
     * <code>repeated .api.v1.BankBranch branches = 1 [json_name = "branches"];</code>
     */
    public com.api.v1.BankBranch.Builder addBranchesBuilder() {
      return internalGetBranchesFieldBuilder().addBuilder(
          com.api.v1.BankBranch.getDefaultInstance());
    }
    /**
     * <code>repeated .api.v1.BankBranch branches = 1 [json_name = "branches"];</code>
     */
    public com.api.v1.BankBranch.Builder addBranchesBuilder(
        int index) {
      return internalGetBranchesFieldBuilder().addBuilder(
          index, com.api.v1.BankBranch.getDefaultInstance());
    }
    /**
     * <code>repeated .api.v1.BankBranch branches = 1 [json_name = "branches"];</code>
     */
    public java.util.List<com.api.v1.BankBranch.Builder> 
         getBranchesBuilderList() {
      return internalGetBranchesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.api.v1.BankBranch, com.api.v1.BankBranch.Builder, com.api.v1.BankBranchOrBuilder> 
        internalGetBranchesFieldBuilder() {
      if (branchesBuilder_ == null) {
        branchesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.api.v1.BankBranch, com.api.v1.BankBranch.Builder, com.api.v1.BankBranchOrBuilder>(
                branches_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        branches_ = null;
      }
      return branchesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:api.v1.SearchBranchesResponse)
  }

  // @@protoc_insertion_point(class_scope:api.v1.SearchBranchesResponse)
  private static final com.api.v1.SearchBranchesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.api.v1.SearchBranchesResponse();
  }

  public static com.api.v1.SearchBranchesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SearchBranchesResponse>
      PARSER = new com.google.protobuf.AbstractParser<SearchBranchesResponse>() {
    @java.lang.Override
    public SearchBranchesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SearchBranchesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SearchBranchesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.api.v1.SearchBranchesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

