// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/bank.proto
// Protobuf Java Version: 4.33.5

package com.api.v1;

@com.google.protobuf.Generated
public interface SearchBanksResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.v1.SearchBanksResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .api.v1.Bank banks = 1 [json_name = "banks"];</code>
   */
  java.util.List<com.api.v1.Bank> 
      getBanksList();
  /**
   * <code>repeated .api.v1.Bank banks = 1 [json_name = "banks"];</code>
   */
  com.api.v1.Bank getBanks(int index);
  /**
   * <code>repeated .api.v1.Bank banks = 1 [json_name = "banks"];</code>
   */
  int getBanksCount();
  /**
   * <code>repeated .api.v1.Bank banks = 1 [json_name = "banks"];</code>
   */
  java.util.List<? extends com.api.v1.BankOrBuilder> 
      getBanksOrBuilderList();
  /**
   * <code>repeated .api.v1.Bank banks = 1 [json_name = "banks"];</code>
   */
  com.api.v1.BankOrBuilder getBanksOrBuilder(
      int index);
}
