// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/payment.proto
// Protobuf Java Version: 4.34.1

package com.api.v1;

@com.google.protobuf.Generated
public interface WithdrawAsyncRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.v1.WithdrawAsyncRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Merchant customer identifier string
   * Must start with "cus-" prefix followed by additional characters
   * This identifier references an existing merchant customer in the system
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>string customer = 1 [json_name = "customer", (.buf.validate.field) = { ... }</code>
   * @return The customer.
   */
  java.lang.String getCustomer();
  /**
   * <pre>
   * Merchant customer identifier string
   * Must start with "cus-" prefix followed by additional characters
   * This identifier references an existing merchant customer in the system
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>string customer = 1 [json_name = "customer", (.buf.validate.field) = { ... }</code>
   * @return The bytes for customer.
   */
  com.google.protobuf.ByteString
      getCustomerBytes();

  /**
   * <pre>
   * The amount to withdraw
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>.api.v1.InitialCharge charge = 2 [json_name = "charge", (.buf.validate.field) = { ... }</code>
   * @return Whether the charge field is set.
   */
  boolean hasCharge();
  /**
   * <pre>
   * The amount to withdraw
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>.api.v1.InitialCharge charge = 2 [json_name = "charge", (.buf.validate.field) = { ... }</code>
   * @return The charge.
   */
  com.api.v1.InitialCharge getCharge();
  /**
   * <pre>
   * The amount to withdraw
   * &#64;gotags: validate:"required"
   * </pre>
   *
   * <code>.api.v1.InitialCharge charge = 2 [json_name = "charge", (.buf.validate.field) = { ... }</code>
   */
  com.api.v1.InitialChargeOrBuilder getChargeOrBuilder();

  /**
   * <pre>
   * Merchant-supplied idempotency key for retry safety.
   * When present, a retry with the same (merchant, idempotency_key) returns the
   * original charge instead of creating a new one. When absent (empty), the
   * server generates a UUID per call (current behavior).
   * ASCII only, 1-255 chars matching ^[a-zA-Z0-9_&#92;-]{1,255}$.
   * </pre>
   *
   * <code>optional string idempotency_key = 3 [json_name = "idempotencyKey", (.buf.validate.field) = { ... }</code>
   * @return Whether the idempotencyKey field is set.
   */
  boolean hasIdempotencyKey();
  /**
   * <pre>
   * Merchant-supplied idempotency key for retry safety.
   * When present, a retry with the same (merchant, idempotency_key) returns the
   * original charge instead of creating a new one. When absent (empty), the
   * server generates a UUID per call (current behavior).
   * ASCII only, 1-255 chars matching ^[a-zA-Z0-9_&#92;-]{1,255}$.
   * </pre>
   *
   * <code>optional string idempotency_key = 3 [json_name = "idempotencyKey", (.buf.validate.field) = { ... }</code>
   * @return The idempotencyKey.
   */
  java.lang.String getIdempotencyKey();
  /**
   * <pre>
   * Merchant-supplied idempotency key for retry safety.
   * When present, a retry with the same (merchant, idempotency_key) returns the
   * original charge instead of creating a new one. When absent (empty), the
   * server generates a UUID per call (current behavior).
   * ASCII only, 1-255 chars matching ^[a-zA-Z0-9_&#92;-]{1,255}$.
   * </pre>
   *
   * <code>optional string idempotency_key = 3 [json_name = "idempotencyKey", (.buf.validate.field) = { ... }</code>
   * @return The bytes for idempotencyKey.
   */
  com.google.protobuf.ByteString
      getIdempotencyKeyBytes();
}
